# Generated by Django 4.2.7 on 2025-07-13 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0002_user_whatsapp_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntelligenceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("sales_trend", "Tendencia de Ventas"),
                            ("inventory_health", "Salud del Inventario"),
                            ("customer_behavior", "Comportamiento del Cliente"),
                            ("supplier_performance", "Rendimiento de Proveedores"),
                            ("profit_margin", "Margen de Ganancia"),
                            ("forecast_accuracy", "Precisión de Pronósticos"),
                        ],
                        max_length=30,
                    ),
                ),
                ("current_value", models.FloatField()),
                ("previous_value", models.FloatField(blank=True, null=True)),
                ("change_percentage", models.FloatField(blank=True, null=True)),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("up", "Subiendo"),
                            ("down", "Bajando"),
                            ("stable", "Estable"),
                        ],
                        default="stable",
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "comparison_period_start",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("comparison_period_end", models.DateTimeField(blank=True, null=True)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("calculation_method", models.CharField(max_length=100)),
                ("raw_data_json", models.JSONField(default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence_metrics",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_metric",
                "ordering": ["-calculated_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "metric_type"],
                        name="intelligenc_company_ada3db_idx",
                    ),
                    models.Index(
                        fields=["calculated_at"], name="intelligenc_calcula_0b4fc3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IntelligenceInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("priority", "Prioridad"),
                            ("opportunity", "Oportunidad"),
                            ("recommendation", "Recomendación"),
                            ("trend", "Tendencia"),
                            ("warning", "Advertencia"),
                            ("forecast", "Pronóstico"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "Alta"),
                            ("medium", "Media"),
                            ("low", "Baja"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("actions_json", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("source_data_json", models.JSONField(default=dict)),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="authentication.company",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_insight",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "insight_type"],
                        name="intelligenc_company_58c2e6_idx",
                    ),
                    models.Index(
                        fields=["priority", "is_active"],
                        name="intelligenc_priorit_26750a_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="intelligenc_created_344c3a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IntelligenceBriefing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "briefing_type",
                    models.CharField(
                        choices=[
                            ("morning", "Briefing Matutino"),
                            ("weekly", "Reporte Semanal"),
                            ("monthly", "Reporte Mensual"),
                            ("custom", "Personalizado"),
                        ],
                        default="morning",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("greeting", models.TextField()),
                ("summary", models.TextField()),
                ("priorities_json", models.JSONField(default=list)),
                ("opportunities_json", models.JSONField(default=list)),
                ("recommendations_json", models.JSONField(default=list)),
                ("metrics_json", models.JSONField(default=dict)),
                ("data_snapshot_json", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="briefings",
                        to="authentication.company",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_briefing",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "briefing_type"],
                        name="intelligenc_company_1f9bbb_idx",
                    ),
                    models.Index(
                        fields=["generated_at"], name="intelligenc_generat_bf8f76_idx"
                    ),
                ],
            },
        ),
    ]
