# Generated by Django 4.2.7 on 2025-07-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataimportsession",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("products", "Productos"),
                    ("suppliers", "Proveedores"),
                    ("categories", "Categorías"),
                    ("customers", "Clientes"),
                    ("leads", "Leads"),
                    ("inventory", "Inventario"),
                    ("transactions", "Transacciones"),
                    ("mixed_products_inventory", "🔀 Productos + Inventario"),
                    ("mixed_sales_products", "🔀 Ventas + Productos"),
                    ("mixed_suppliers_products", "🔀 Proveedores + Productos"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="fielddefinition",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("products", "Productos"),
                    ("suppliers", "Proveedores"),
                    ("categories", "Categorías"),
                    ("customers", "Clientes"),
                    ("leads", "Leads"),
                    ("inventory", "Inventario"),
                    ("transactions", "Transacciones"),
                    ("mixed_products_inventory", "🔀 Productos + Inventario"),
                    ("mixed_sales_products", "🔀 Ventas + Productos"),
                    ("mixed_suppliers_products", "🔀 Proveedores + Productos"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="importtemplate",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("products", "Productos"),
                    ("suppliers", "Proveedores"),
                    ("categories", "Categorías"),
                    ("customers", "Clientes"),
                    ("leads", "Leads"),
                    ("inventory", "Inventario"),
                    ("transactions", "Transacciones"),
                    ("mixed_products_inventory", "🔀 Productos + Inventario"),
                    ("mixed_sales_products", "🔀 Ventas + Productos"),
                    ("mixed_suppliers_products", "🔀 Proveedores + Productos"),
                ],
                max_length=50,
            ),
        ),
    ]
