# Generated by Django 4.2.7 on 2025-07-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0002_alter_dataimportsession_import_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataimportsession",
            name="import_type",
            field=models.CharField(max_length=100),
        ),
    ]
