# Generated by Django 4.2.7 on 2025-07-03 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_managers"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("product", "Producto"),
                            ("supplier", "Proveedor"),
                            ("category", "Categoría"),
                            ("inventory_item", "Item de Inventario"),
                            ("transaction", "Transacción"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="Nombre del campo"),
                ),
                (
                    "field_label",
                    models.CharField(max_length=200, verbose_name="Etiqueta mostrada"),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("number", "Número"),
                            ("decimal", "Decimal"),
                            ("date", "Fecha"),
                            ("datetime", "Fecha y Hora"),
                            ("boolean", "Sí/No"),
                            ("choice", "Lista de opciones"),
                            ("email", "Email"),
                            ("url", "URL"),
                            ("phone", "Teléfono"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, verbose_name="Campo obligatorio"
                    ),
                ),
                (
                    "default_value",
                    models.TextField(blank=True, verbose_name="Valor por defecto"),
                ),
                (
                    "help_text",
                    models.TextField(blank=True, verbose_name="Texto de ayuda"),
                ),
                (
                    "choices_json",
                    models.TextField(
                        blank=True,
                        help_text="Para campos de tipo 'choice', formato: [{'value': 'val1', 'label': 'Label 1'}]",
                        verbose_name="Opciones (JSON)",
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("min_length", models.IntegerField(blank=True, null=True)),
                ("max_length", models.IntegerField(blank=True, null=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, verbose_name="Orden de visualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_definitions",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "ordering": ["model_type", "order", "field_name"],
                "unique_together": {("company", "model_type", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("text_value", models.TextField(blank=True)),
                ("number_value", models.BigIntegerField(blank=True, null=True)),
                (
                    "decimal_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("date_value", models.DateField(blank=True, null=True)),
                ("datetime_value", models.DateTimeField(blank=True, null=True)),
                ("boolean_value", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "custom_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="inventory.customfielddefinition",
                    ),
                ),
            ],
            options={
                "unique_together": {("custom_field", "content_type", "object_id")},
            },
        ),
    ]
