# Generated by Django 4.2.7 on 2025-07-12 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Perú", max_length=100, verbose_name="País"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=20, verbose_name="RUC/DNI"),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Persona Natural"),
                            ("business", "Empresa"),
                        ],
                        default="individual",
                        max_length=20,
                        verbose_name="Tipo de cliente",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Límite de crédito",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="authentication.company",
                verbose_name="Empresa",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Empresa"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "Sitio Web"),
                            ("phone", "Llamada"),
                            ("email", "Email"),
                            ("referral", "Referido"),
                            ("social", "Redes Sociales"),
                            ("other", "Otro"),
                        ],
                        default="web",
                        max_length=50,
                        verbose_name="Fuente",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nuevo"),
                            ("contacted", "Contactado"),
                            ("qualified", "Calificado"),
                            ("proposal", "Propuesta"),
                            ("negotiation", "Negociación"),
                            ("won", "Ganado"),
                            ("lost", "Perdido"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor estimado",
                    ),
                ),
                (
                    "expected_close_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha estimada de cierre"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado a",
                    ),
                ),
                (
                    "interested_products",
                    models.ManyToManyField(
                        blank=True,
                        to="inventory.product",
                        verbose_name="Productos de interés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
