# Generated by Django 4.2.7 on 2025-07-06 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0002_alter_user_managers"),
        ("inventory", "0002_customfielddefinition_customfieldvalue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Persona Natural"),
                            ("business", "Empresa"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("inactive", "Inactivo"),
                            ("prospect", "Prospecto"),
                            ("churned", "Perdido"),
                        ],
                        default="prospect",
                        max_length=20,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nombres"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Apellidos"
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Razón Social"
                    ),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre Comercial"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Tipo de Documento"
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número de Documento"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=20, verbose_name="Celular"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=100, verbose_name="Región"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Perú", max_length=100, verbose_name="País"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Código Postal"
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Industria"
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tamaño de Empresa"
                    ),
                ),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Ingresos Anuales",
                    ),
                ),
                (
                    "acquisition_source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fuente de Adquisición"
                    ),
                ),
                (
                    "first_contact_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Primer Contacto"
                    ),
                ),
                (
                    "last_contact_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Último Contacto"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_customers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado a",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["-created_at"],
            },
            bases=(inventory.models.CustomFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Empresa"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(blank=True, max_length=100, verbose_name="Cargo"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nuevo"),
                            ("contacted", "Contactado"),
                            ("qualified", "Calificado"),
                            ("proposal", "Propuesta"),
                            ("negotiation", "Negociación"),
                            ("won", "Ganado"),
                            ("lost", "Perdido"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Sitio Web"),
                            ("social_media", "Redes Sociales"),
                            ("email_marketing", "Email Marketing"),
                            ("referral", "Referencia"),
                            ("cold_call", "Llamada Fría"),
                            ("event", "Evento"),
                            ("advertisement", "Publicidad"),
                            ("other", "Otro"),
                        ],
                        default="website",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(default=0, verbose_name="Puntaje del Lead"),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Industria"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Presupuesto",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "expected_close_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Cierre Esperada"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado a",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
            bases=(inventory.models.CustomFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Oportunidad"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("prospecting", "Prospección"),
                            ("qualification", "Calificación"),
                            ("needs_analysis", "Análisis de Necesidades"),
                            ("value_proposition", "Propuesta de Valor"),
                            ("decision_makers", "Tomadores de Decisión"),
                            ("perception_analysis", "Análisis de Percepción"),
                            ("proposal", "Propuesta"),
                            ("negotiation", "Negociación"),
                            ("closed_won", "Cerrado Ganado"),
                            ("closed_lost", "Cerrado Perdido"),
                        ],
                        default="prospecting",
                        max_length=30,
                    ),
                ),
                (
                    "probability",
                    models.IntegerField(default=0, verbose_name="Probabilidad (%)"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="PEN", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "expected_close_date",
                    models.DateField(verbose_name="Fecha Cierre Esperada"),
                ),
                (
                    "actual_close_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Cierre Real"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_opportunities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado a",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="authentication.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="inventory.customer",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="inventory.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oportunidad",
                "verbose_name_plural": "Oportunidades",
                "ordering": ["-created_at"],
            },
            bases=(inventory.models.CustomFieldMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="customfielddefinition",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("product", "Producto"),
                    ("supplier", "Proveedor"),
                    ("category", "Categoría"),
                    ("inventory_item", "Item de Inventario"),
                    ("transaction", "Transacción"),
                    ("customer", "Cliente"),
                    ("lead", "Lead"),
                    ("opportunity", "Oportunidad"),
                    ("contact", "Contacto"),
                    ("activity", "Actividad"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="OpportunityProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.opportunity",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="opportunity",
            name="products",
            field=models.ManyToManyField(
                related_name="opportunities",
                through="inventory.OpportunityProduct",
                to="inventory.product",
            ),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                (
                    "job_title",
                    models.CharField(blank=True, max_length=100, verbose_name="Cargo"),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("primary", "Contacto Principal"),
                            ("secondary", "Contacto Secundario"),
                            ("technical", "Contacto Técnico"),
                            ("billing", "Contacto de Facturación"),
                            ("decision_maker", "Tomador de Decisiones"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=20, verbose_name="Celular"),
                ),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn")),
                (
                    "twitter",
                    models.CharField(blank=True, max_length=50, verbose_name="Twitter"),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Departamento"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="Cumpleaños"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="authentication.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="inventory.customer",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="inventory.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacto",
                "verbose_name_plural": "Contactos",
                "ordering": ["last_name", "first_name"],
            },
            bases=(inventory.models.CustomFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("call", "Llamada"),
                            ("email", "Email"),
                            ("meeting", "Reunión"),
                            ("task", "Tarea"),
                            ("note", "Nota"),
                            ("demo", "Demostración"),
                            ("proposal", "Propuesta"),
                            ("follow_up", "Seguimiento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planificado"),
                            ("in_progress", "En Progreso"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(verbose_name="Fecha Programada"),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Completada"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duración (minutos)"
                    ),
                ),
                ("outcome", models.TextField(blank=True, verbose_name="Resultado")),
                (
                    "next_action",
                    models.TextField(blank=True, verbose_name="Próxima Acción"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado a",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="authentication.company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="inventory.contact",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="inventory.customer",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="inventory.lead",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="inventory.opportunity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "ordering": ["-scheduled_date"],
            },
        ),
    ]
