# Generated by Django 4.2.7 on 2025-07-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_customer_product_company_lead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateTimeField(),
        ),
    ]
