# Generated by Django 4.2.7 on 2025-07-19 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_whatsapp_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0005_purchase_order_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la campaña"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "track_opens",
                    models.BooleanField(
                        default=True, verbose_name="Trackear aperturas"
                    ),
                ),
                (
                    "track_clicks",
                    models.BooleanField(default=True, verbose_name="Trackear clicks"),
                ),
                (
                    "total_sent",
                    models.IntegerField(default=0, verbose_name="Total enviados"),
                ),
                (
                    "total_delivered",
                    models.IntegerField(default=0, verbose_name="Total entregados"),
                ),
                (
                    "total_opened",
                    models.IntegerField(default=0, verbose_name="Total abiertos"),
                ),
                (
                    "total_clicked",
                    models.IntegerField(default=0, verbose_name="Total con clicks"),
                ),
                (
                    "total_bounced",
                    models.IntegerField(default=0, verbose_name="Total rebotados"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_campaigns",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_email_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaña de Email",
                "verbose_name_plural": "Campañas de Email",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrackedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_id",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="ID del email"
                    ),
                ),
                (
                    "tracking_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID de tracking"
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        max_length=254, verbose_name="Email destinatario"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre destinatario"
                    ),
                ),
                ("subject", models.CharField(max_length=500, verbose_name="Asunto")),
                (
                    "content_preview",
                    models.TextField(
                        blank=True, verbose_name="Vista previa del contenido"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviado"),
                            ("delivered", "Entregado"),
                            ("opened", "Abierto"),
                            ("clicked", "Con clicks"),
                            ("replied", "Respondido"),
                            ("bounced", "Rebotado"),
                            ("failed", "Falló"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado en"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entregado en"
                    ),
                ),
                (
                    "first_opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Primera apertura"
                    ),
                ),
                (
                    "last_opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última apertura"
                    ),
                ),
                (
                    "first_clicked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Primer click"
                    ),
                ),
                (
                    "last_clicked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último click"
                    ),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Respondido en"
                    ),
                ),
                (
                    "bounced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rebotado en"
                    ),
                ),
                (
                    "open_count",
                    models.IntegerField(default=0, verbose_name="Número de aperturas"),
                ),
                (
                    "click_count",
                    models.IntegerField(default=0, verbose_name="Número de clicks"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "location_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos de ubicación"
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Información del dispositivo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracked_emails",
                        to="inventory.emailcampaign",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_emails",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Tracked",
                "verbose_name_plural": "Emails Tracked",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GmailWebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "history_id",
                    models.CharField(max_length=100, verbose_name="History ID"),
                ),
                (
                    "email_address",
                    models.EmailField(max_length=254, verbose_name="Email address"),
                ),
                ("raw_payload", models.JSONField(verbose_name="Payload completo")),
                (
                    "processed_changes",
                    models.JSONField(default=list, verbose_name="Cambios procesados"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Procesado en"
                    ),
                ),
                (
                    "processing_success",
                    models.BooleanField(
                        default=True, verbose_name="Procesamiento exitoso"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gmail_webhook_logs",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Webhook Gmail",
                "verbose_name_plural": "Logs de Webhooks Gmail",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("time_peak", "Pico de Tiempo"),
                            ("sender_frequency", "Frecuencia de Remitente"),
                            ("subject_similarity", "Similitud de Asunto"),
                            ("content_category", "Categoría de Contenido"),
                            ("engagement_trend", "Tendencia de Engagement"),
                            ("ai_insight", "Insight de IA"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de patrón",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del patrón"),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                ("frequency", models.IntegerField(verbose_name="Frecuencia")),
                ("confidence", models.FloatField(verbose_name="Confianza (0-1)")),
                (
                    "impact_score",
                    models.FloatField(default=0, verbose_name="Puntuación de impacto"),
                ),
                (
                    "pattern_data",
                    models.JSONField(default=dict, verbose_name="Datos del patrón"),
                ),
                ("examples", models.JSONField(default=list, verbose_name="Ejemplos")),
                (
                    "recommendation",
                    models.TextField(blank=True, verbose_name="Recomendación"),
                ),
                (
                    "action_items",
                    models.JSONField(default=list, verbose_name="Elementos de acción"),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Detectado en"
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(verbose_name="Inicio del período"),
                ),
                ("period_end", models.DateTimeField(verbose_name="Fin del período")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_patterns",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patrón de Email",
                "verbose_name_plural": "Patrones de Email",
                "ordering": ["-detected_at", "-confidence"],
            },
        ),
        migrations.CreateModel(
            name="EmailInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("opportunity", "Oportunidad"),
                            ("optimization", "Optimización"),
                            ("risk", "Riesgo"),
                            ("automation", "Automatización"),
                            ("behavior", "Comportamiento"),
                            ("trend", "Tendencia"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de insight",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "confidence_score",
                    models.FloatField(verbose_name="Puntuación de confianza"),
                ),
                (
                    "impact_potential",
                    models.FloatField(default=0, verbose_name="Potencial de impacto"),
                ),
                (
                    "action_items",
                    models.JSONField(default=list, verbose_name="Elementos de acción"),
                ),
                (
                    "expected_outcome",
                    models.TextField(blank=True, verbose_name="Resultado esperado"),
                ),
                (
                    "is_implemented",
                    models.BooleanField(default=False, verbose_name="Implementado"),
                ),
                (
                    "implemented_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Implementado en"
                    ),
                ),
                (
                    "implementation_notes",
                    models.TextField(
                        blank=True, verbose_name="Notas de implementación"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Generado en"),
                ),
                (
                    "generated_by_ai",
                    models.BooleanField(default=True, verbose_name="Generado por IA"),
                ),
                (
                    "source_data_period",
                    models.JSONField(
                        default=dict, verbose_name="Período de datos fuente"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_insights",
                        to="authentication.company",
                    ),
                ),
                (
                    "related_patterns",
                    models.ManyToManyField(
                        blank=True, related_name="insights", to="inventory.emailpattern"
                    ),
                ),
            ],
            options={
                "verbose_name": "Insight de Email",
                "verbose_name_plural": "Insights de Email",
                "ordering": ["-priority", "-confidence_score", "-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL clickeada")),
                (
                    "link_text",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Texto del enlace"
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Posición en el email"
                    ),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Clickeado en"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                ("referrer", models.URLField(blank=True, verbose_name="Referrer")),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tipo de dispositivo"
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Navegador"
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Sistema operativo"
                    ),
                ),
                (
                    "tracked_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="inventory.trackedemail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Click de Email",
                "verbose_name_plural": "Clicks de Email",
                "ordering": ["-clicked_at"],
            },
        ),
        migrations.AddIndex(
            model_name="trackedemail",
            index=models.Index(
                fields=["tracking_id"], name="inventory_t_trackin_94a7f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trackedemail",
            index=models.Index(
                fields=["company", "status"], name="inventory_t_company_af5ca7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trackedemail",
            index=models.Index(
                fields=["recipient_email"], name="inventory_t_recipie_363fb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trackedemail",
            index=models.Index(
                fields=["sent_at"], name="inventory_t_sent_at_3fda01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gmailwebhooklog",
            index=models.Index(
                fields=["company", "history_id"], name="inventory_g_company_b68939_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gmailwebhooklog",
            index=models.Index(
                fields=["processed_at"], name="inventory_g_process_9f54ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailpattern",
            index=models.Index(
                fields=["company", "pattern_type"],
                name="inventory_e_company_5c52fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailpattern",
            index=models.Index(
                fields=["confidence", "impact_score"],
                name="inventory_e_confide_42af13_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailinsight",
            index=models.Index(
                fields=["company", "insight_type"],
                name="inventory_e_company_bb03fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailinsight",
            index=models.Index(
                fields=["priority", "is_implemented"],
                name="inventory_e_priorit_ff2cf9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailclick",
            index=models.Index(
                fields=["tracked_email", "clicked_at"],
                name="inventory_e_tracked_4d2e8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailclick",
            index=models.Index(fields=["url"], name="inventory_e_url_3741a6_idx"),
        ),
        migrations.AddIndex(
            model_name="emailcampaign",
            index=models.Index(
                fields=["company", "is_active"], name="inventory_e_company_b3da08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailcampaign",
            index=models.Index(
                fields=["created_at"], name="inventory_e_created_dc2412_idx"
            ),
        ),
    ]
