# Generated by Django 4.2.7 on 2025-07-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_add_email_tracking_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="email_tracking_campaign_id",
            field=models.UUIDField(
                blank=True,
                help_text="ID de la campaña de email para analytics",
                null=True,
                verbose_name="ID de Campaña de Email",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="tracking_id",
            field=models.CharField(
                blank=True,
                help_text="ID para seguimiento automático del email enviado",
                max_length=100,
                null=True,
                verbose_name="ID de Tracking del Email",
            ),
        ),
    ]
