# Generated by Django 4.2.7 on 2025-07-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_add_email_tracking_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="sent_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("whatsapp", "WhatsApp"),
                    ("both", "Ambos"),
                ],
                max_length=20,
                null=True,
                verbose_name="Método de Envío",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier_whatsapp",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="WhatsApp del Proveedor",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="whatsapp_message_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ID del Mensaje WhatsApp",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="whatsapp_sent",
            field=models.BooleanField(default=False, verbose_name="WhatsApp Enviado"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="whatsapp_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Envío de WhatsApp"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="delivery_days",
            field=models.PositiveIntegerField(
                default=7, verbose_name="Días de entrega"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="minimum_order_quantity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Cantidad mínima de orden"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="prefers_whatsapp",
            field=models.BooleanField(
                default=False,
                help_text="Si está habilitado, se enviará por WhatsApp antes que por email",
                verbose_name="Prefiere WhatsApp",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="whatsapp_enabled",
            field=models.BooleanField(
                default=False, verbose_name="WhatsApp habilitado"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text="Formato: +51999999999",
                max_length=20,
                verbose_name="Número WhatsApp",
            ),
        ),
    ]
