# Generated by Django 4.2.7 on 2025-07-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_add_whatsapp_to_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="delivery_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tiempo estimado de entrega en días (varía según origen y producto)",
                null=True,
                verbose_name="Días de entrega",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="minimum_order_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Cantidad mínima que acepta el proveedor por orden",
                null=True,
                verbose_name="Cantidad mínima de orden",
            ),
        ),
    ]
