# Generated by Django 4.2.7 on 2025-07-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_company_custom_whatsapp_config_and_more"),
        ("inventory", "0009_update_supplier_order_fields_flexible"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "twilio_account_sid",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Twilio Account SID",
                    ),
                ),
                (
                    "twilio_auth_token",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Twilio Auth Token",
                    ),
                ),
                (
                    "whatsapp_from_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Número WhatsApp Business",
                    ),
                ),
                (
                    "gmail_access_token",
                    models.TextField(
                        blank=True, null=True, verbose_name="Gmail Access Token"
                    ),
                ),
                (
                    "gmail_refresh_token",
                    models.TextField(
                        blank=True, null=True, verbose_name="Gmail Refresh Token"
                    ),
                ),
                (
                    "gmail_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email Gmail Configurado",
                    ),
                ),
                (
                    "is_whatsapp_active",
                    models.BooleanField(default=False, verbose_name="WhatsApp Activo"),
                ),
                (
                    "is_gmail_active",
                    models.BooleanField(default=False, verbose_name="Gmail Activo"),
                ),
                (
                    "n8n_webhook_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL Webhook n8n"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_config",
                        to="authentication.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Tenant",
                "verbose_name_plural": "Configuraciones de Tenants",
            },
        ),
    ]
