# Generated by Django 4.2.7 on 2025-07-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_create_tenant_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconfig",
            name="gmail_client_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Gmail Client ID"
            ),
        ),
        migrations.AddField(
            model_name="tenantconfig",
            name="gmail_client_secret",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Gmail Client Secret",
            ),
        ),
        migrations.AddField(
            model_name="tenantconfig",
            name="oauth2_client_id",
            field=models.CharField(
                default="aLwAD2L646ewX870AnPfl5aI8lBHrQx3PtBiPTty",
                max_length=255,
                verbose_name="OAuth2 Client ID",
            ),
        ),
        migrations.AddField(
            model_name="tenantconfig",
            name="oauth2_client_secret",
            field=models.CharField(
                default="pbkdf2_sha256$600000$2eDlCGhB2yarISowS46A7B$wNAsGkOon/0IPStVxRRE1V7pvsEp8lVzkrFlu13Eya8=",
                max_length=255,
                verbose_name="OAuth2 Client Secret",
            ),
        ),
        migrations.AddField(
            model_name="tenantconfig",
            name="oauth2_token_url",
            field=models.URLField(
                default="https://016e520d8ade.ngrok-free.app/oauth/token/",
                verbose_name="OAuth2 Token URL",
            ),
        ),
    ]
