# Generated by Django 4.2.7 on 2025-07-11 17:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KPIDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del KPI"),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                ("code", models.CharField(max_length=50, verbose_name="Código único")),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("sum", "Suma"),
                            ("average", "Promedio"),
                            ("count", "Conteo"),
                            ("percentage", "Porcentaje"),
                            ("ratio", "Ratio"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de cálculo",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("inventory", "Inventario"),
                            ("transactions", "Transacciones"),
                            ("forecasts", "Pronósticos"),
                            ("alerts", "Alertas"),
                            ("products", "Productos"),
                            ("suppliers", "Proveedores"),
                        ],
                        max_length=20,
                        verbose_name="Fuente de datos",
                    ),
                ),
                (
                    "formula",
                    models.TextField(
                        blank=True,
                        help_text="Fórmula SQL o expresión para cálculos personalizados",
                        verbose_name="Fórmula",
                    ),
                ),
                (
                    "default_filters",
                    models.JSONField(default=dict, verbose_name="Filtros por defecto"),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=20, verbose_name="Unidad"),
                ),
                (
                    "decimal_places",
                    models.PositiveIntegerField(default=2, verbose_name="Decimales"),
                ),
                (
                    "show_as_percentage",
                    models.BooleanField(
                        default=False, verbose_name="Mostrar como porcentaje"
                    ),
                ),
                (
                    "good_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Umbral bueno",
                    ),
                ),
                (
                    "warning_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Umbral advertencia",
                    ),
                ),
                (
                    "critical_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Umbral crítico",
                    ),
                ),
                (
                    "track_trend",
                    models.BooleanField(default=True, verbose_name="Seguir tendencia"),
                ),
                (
                    "trend_periods",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Períodos de tendencia"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="KPI activo"),
                ),
                (
                    "is_system_kpi",
                    models.BooleanField(default=False, verbose_name="KPI del sistema"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden de visualización"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_definitions",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_kpi_definitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Definición de KPI",
                "verbose_name_plural": "Definiciones de KPIs",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Título del reporte"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("generating", "Generando"),
                            ("completed", "Completado"),
                            ("failed", "Falló"),
                            ("sent", "Enviado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, verbose_name="Parámetros del reporte"
                    ),
                ),
                (
                    "filters_applied",
                    models.JSONField(default=dict, verbose_name="Filtros aplicados"),
                ),
                ("date_from", models.DateField(verbose_name="Fecha desde")),
                ("date_to", models.DateField(verbose_name="Fecha hasta")),
                (
                    "file_format",
                    models.CharField(max_length=20, verbose_name="Formato del archivo"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Ruta del archivo"
                    ),
                ),
                (
                    "file_size_mb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Tamaño del archivo (MB)",
                    ),
                ),
                (
                    "total_records",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Total de registros"
                    ),
                ),
                (
                    "generation_time_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Tiempo de generación (segundos)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "execution_log",
                    models.TextField(blank=True, verbose_name="Log de ejecución"),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del reporte"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("inventory_summary", "Resumen de Inventario"),
                            ("stock_movement", "Movimiento de Stock"),
                            ("abc_analysis", "Análisis ABC"),
                            ("turnover_analysis", "Análisis de Rotación"),
                            ("forecast_accuracy", "Precisión de Pronósticos"),
                            ("alerts_summary", "Resumen de Alertas"),
                            ("supplier_performance", "Rendimiento de Proveedores"),
                            ("product_performance", "Rendimiento de Productos"),
                            ("cost_analysis", "Análisis de Costos"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de reporte",
                    ),
                ),
                (
                    "default_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        default="pdf",
                        max_length=20,
                        verbose_name="Formato por defecto",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("on_demand", "Bajo demanda"),
                            ("daily", "Diario"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                        ],
                        default="on_demand",
                        max_length=20,
                        verbose_name="Frecuencia",
                    ),
                ),
                (
                    "default_filters",
                    models.JSONField(default=dict, verbose_name="Filtros por defecto"),
                ),
                (
                    "columns_config",
                    models.JSONField(
                        default=list, verbose_name="Configuración de columnas"
                    ),
                ),
                (
                    "charts_config",
                    models.JSONField(
                        default=list, verbose_name="Configuración de gráficos"
                    ),
                ),
                (
                    "grouping_config",
                    models.JSONField(
                        default=dict, verbose_name="Configuración de agrupación"
                    ),
                ),
                (
                    "sorting_config",
                    models.JSONField(
                        default=list, verbose_name="Configuración de ordenamiento"
                    ),
                ),
                (
                    "auto_send",
                    models.BooleanField(default=False, verbose_name="Envío automático"),
                ),
                (
                    "additional_emails",
                    models.TextField(
                        blank=True,
                        help_text="Emails adicionales separados por comas",
                        verbose_name="Emails adicionales",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Plantilla activa"),
                ),
                (
                    "is_system_template",
                    models.BooleanField(
                        default=False, verbose_name="Plantilla del sistema"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_report_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatarios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de reporte",
                "verbose_name_plural": "Plantillas de reportes",
                "ordering": ["-created_at"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la programación"
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("daily", "Diario"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de programación",
                    ),
                ),
                (
                    "hour",
                    models.PositiveIntegerField(
                        default=9,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                        verbose_name="Hora",
                    ),
                ),
                (
                    "minute",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ],
                        verbose_name="Minuto",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="0=Lunes, 6=Domingo",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="Día de la semana",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Día del mes",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Programación activa"
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_run_status",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Estado última ejecución",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_report_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programación de reporte",
                "verbose_name_plural": "Programaciones de reportes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distribution_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("download", "Descarga"),
                            ("api", "API"),
                            ("ftp", "FTP"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de distribución",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviado"),
                            ("failed", "Falló"),
                            ("delivered", "Entregado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        default=list, verbose_name="Lista de destinatarios"
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "delivery_details",
                    models.JSONField(default=dict, verbose_name="Detalles de entrega"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribución de reporte",
                "verbose_name_plural": "Distribuciones de reportes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="report",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_reports",
                to="reports.reporttemplate",
            ),
        ),
        migrations.CreateModel(
            name="KPIValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Inicio del período")),
                ("period_end", models.DateField(verbose_name="Fin del período")),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Diario"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                            ("yearly", "Anual"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de período",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="Valor"
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(default=dict, verbose_name="Datos de contexto"),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calculation_duration_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duración del cálculo (ms)"
                    ),
                ),
                (
                    "kpi_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="reports.kpidefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de KPI",
                "verbose_name_plural": "Valores de KPIs",
                "ordering": ["-period_end"],
            },
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["template", "status"], name="reports_rep_templat_1bd53d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["requested_by", "created_at"],
                name="reports_rep_request_0cedb3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kpivalue",
            index=models.Index(
                fields=["kpi_definition", "period_end"],
                name="reports_kpi_kpi_def_0b5c0c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kpivalue",
            unique_together={("kpi_definition", "period_start", "period_end")},
        ),
        migrations.AlterUniqueTogether(
            name="kpidefinition",
            unique_together={("company", "code")},
        ),
    ]
