# Generated by Django 4.2.7 on 2025-07-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distribution_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("download", "Descarga"),
                            ("api", "API"),
                            ("ftp", "FTP"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de distribución",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviado"),
                            ("failed", "Falló"),
                            ("delivered", "Entregado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        default=list, verbose_name="Lista de destinatarios"
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "delivery_details",
                    models.JSONField(default=dict, verbose_name="Detalles de entrega"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribución de reporte",
                "verbose_name_plural": "Distribuciones de reportes",
                "ordering": ["-created_at"],
            },
        ),
    ]
