# Generated by Django 4.2.7 on 2025-07-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="whatsapp_notifications",
            field=models.BooleanField(
                default=False, verbose_name="Notificaciones por WhatsApp"
            ),
        ),
    ]
