# Generated by Django 4.2.7 on 2025-07-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_whatsapp_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="custom_whatsapp_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Solo para plan Enterprise",
                verbose_name="Configuración WhatsApp personalizada",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="whatsapp_business_number",
            field=models.CharField(
                blank=True,
                help_text="Número que verán los clientes (puede ser virtual)",
                max_length=20,
                null=True,
                verbose_name="Número WhatsApp de Display",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="whatsapp_enabled",
            field=models.BooleanField(
                default=False, verbose_name="WhatsApp habilitado"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="whatsapp_plan",
            field=models.CharField(
                choices=[
                    ("basic", "Básico - Número compartido"),
                    ("premium", "Premium - Número dedicado"),
                    ("enterprise", "Enterprise - API propia"),
                ],
                default="basic",
                max_length=20,
                verbose_name="Plan WhatsApp",
            ),
        ),
    ]
