# Generated by Django 4.2.7 on 2025-07-21 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_company_custom_whatsapp_config_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantConfig",
            fields=[
                (
                    "tenant_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del tenant"),
                ),
                (
                    "domain",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Dominio"
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        max_length=254, verbose_name="Dirección de email"
                    ),
                ),
                (
                    "phone_number_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID del número de teléfono WhatsApp",
                    ),
                ),
                (
                    "wa_token",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Token de WhatsApp (encriptado)",
                    ),
                ),
                (
                    "gsuite_key",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Clave de G Suite (encriptado)",
                    ),
                ),
                (
                    "dkim_selector",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Selector DKIM",
                    ),
                ),
                (
                    "dns_zone_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID de zona DNS",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Tenant activo"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("domain_verified", "Dominio verificado"),
                            ("email_configured", "Email configurado"),
                            ("whatsapp_configured", "WhatsApp configurado"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado de verificación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Tenant",
                "verbose_name_plural": "Configuraciones de Tenant",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("ocr", "OCR"),
                            ("ia", "IA"),
                        ],
                        max_length=20,
                        verbose_name="Canal",
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="Acción")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("success", "Éxito"),
                            ("failed", "Fallido"),
                            ("retry", "Reintentando"),
                        ],
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Detalles"),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4, verbose_name="ID de solicitud"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de reintentos"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de error"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="authentication.tenantconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Uso",
                "verbose_name_plural": "Logs de Uso",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "channel", "timestamp"],
                        name="authenticat_tenant__319583_idx",
                    ),
                    models.Index(
                        fields=["status", "timestamp"],
                        name="authenticat_status_12df40_idx",
                    ),
                ],
            },
        ),
    ]
