# Generated by Django 4.2.7 on 2025-07-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_tenantconfig_usagelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconfig",
            name="client_secret",
            field=models.CharField(
                blank=True,
                help_text="Secret key para autenticación de APIs externas",
                max_length=128,
                null=True,
                verbose_name="Client Secret para N8N",
            ),
        ),
    ]
