# Generated by Django 4.2.7 on 2025-07-21 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_tenantconfig_client_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantAIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI GPT"),
                            ("claude", "Claude"),
                            ("gemini", "Google Gemini"),
                            ("custom", "API Personalizada"),
                            ("disabled", "Deshabilitado"),
                        ],
                        default="openai",
                        max_length=20,
                        verbose_name="Proveedor de IA",
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.TextField(blank=True, verbose_name="API Key (Encriptada)"),
                ),
                (
                    "custom_api_url",
                    models.URLField(blank=True, verbose_name="URL API Personalizada"),
                ),
                (
                    "default_tone",
                    models.CharField(
                        choices=[
                            ("formal", "Formal"),
                            ("casual", "Casual"),
                            ("friendly", "Amigable"),
                            ("professional", "Profesional"),
                            ("enthusiastic", "Entusiasta"),
                            ("custom", "Personalizado"),
                        ],
                        default="friendly",
                        max_length=20,
                        verbose_name="Tono por defecto",
                    ),
                ),
                (
                    "brand_voice_description",
                    models.TextField(
                        blank=True,
                        help_text="Describe cómo debe sonar tu marca: profesional, cercana, técnica, etc.",
                        verbose_name="Descripción de la voz de marca",
                    ),
                ),
                (
                    "custom_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instrucciones específicas para la IA sobre tu negocio",
                        verbose_name="Instrucciones personalizadas",
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        default=150, verbose_name="Máximo tokens"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="0.0 = Respuestas consistentes, 1.0 = Respuestas creativas",
                        verbose_name="Temperatura (0.0-1.0)",
                    ),
                ),
                (
                    "include_customer_history",
                    models.BooleanField(
                        default=True, verbose_name="Incluir historial del cliente"
                    ),
                ),
                (
                    "include_product_info",
                    models.BooleanField(
                        default=True, verbose_name="Incluir información de productos"
                    ),
                ),
                (
                    "daily_ai_limit",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Máximo número de mensajes con IA por día",
                        verbose_name="Límite diario de IA",
                    ),
                ),
                (
                    "require_human_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Los mensajes de IA requieren aprobación antes de enviar",
                        verbose_name="Requiere aprobación humana",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_config",
                        to="authentication.tenantconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de IA",
                "verbose_name_plural": "Configuraciones de IA",
            },
        ),
        migrations.CreateModel(
            name="TenantCommunicationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("order_confirmed", "Pedido Confirmado"),
                            ("order_preparing", "Pedido en Preparación"),
                            ("order_ready", "Pedido Listo"),
                            ("order_delivered", "Pedido Entregado"),
                            ("order_cancelled", "Pedido Cancelado"),
                            ("payment_confirmed", "Pago Confirmado"),
                            ("payment_failed", "Pago Fallido"),
                            ("appointment_confirmed", "Cita Confirmada"),
                            ("appointment_reminder", "Recordatorio de Cita"),
                            ("service_completed", "Servicio Completado"),
                            ("promotional", "Promocional"),
                            ("support", "Soporte"),
                            ("inventory_low", "Stock Bajo"),
                            ("inventory_out", "Sin Stock"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Evento",
                    ),
                ),
                (
                    "channel_preference",
                    models.CharField(
                        choices=[
                            ("whatsapp_only", "Solo WhatsApp"),
                            ("email_only", "Solo Email"),
                            ("both_whatsapp_primary", "Ambos (WhatsApp Principal)"),
                            ("both_email_primary", "Ambos (Email Principal)"),
                            ("disabled", "Deshabilitado"),
                        ],
                        max_length=30,
                        verbose_name="Preferencia de Canal",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("normal", "Normal"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "use_ai_personalization",
                    models.BooleanField(
                        default=True, verbose_name="Usar IA para personalizar"
                    ),
                ),
                (
                    "custom_message_template",
                    models.TextField(
                        blank=True, verbose_name="Plantilla personalizada"
                    ),
                ),
                (
                    "send_immediately",
                    models.BooleanField(
                        default=True, verbose_name="Enviar inmediatamente"
                    ),
                ),
                (
                    "delay_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Retraso en minutos"
                    ),
                ),
                (
                    "respect_business_hours",
                    models.BooleanField(
                        default=False, verbose_name="Respetar horario comercial"
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Máximo reintentos"
                    ),
                ),
                (
                    "fallback_channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("whatsapp_only", "Solo WhatsApp"),
                            ("email_only", "Solo Email"),
                            ("both_whatsapp_primary", "Ambos (WhatsApp Principal)"),
                            ("both_email_primary", "Ambos (Email Principal)"),
                            ("disabled", "Deshabilitado"),
                        ],
                        max_length=30,
                        verbose_name="Canal de respaldo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_configs",
                        to="authentication.tenantconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Comunicación",
                "verbose_name_plural": "Configuraciones de Comunicación",
                "ordering": ["event_type"],
                "unique_together": {("tenant", "event_type")},
            },
        ),
    ]
