# Generated by Django 4.2.7 on 2025-07-11 17:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("message", models.TextField(verbose_name="Mensaje")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Severidad",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("acknowledged", "Reconocida"),
                            ("resolved", "Resuelta"),
                            ("dismissed", "Descartada"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor actual",
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor umbral",
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(default=dict, verbose_name="Datos de contexto"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre de la regla"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Stock bajo"),
                            ("high_stock", "Stock alto"),
                            ("expiration", "Próximo a vencer"),
                            ("expired", "Vencido"),
                            ("high_demand", "Demanda alta"),
                            ("no_movement", "Sin movimiento"),
                            ("negative_stock", "Stock negativo"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de alerta",
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor umbral",
                    ),
                ),
                (
                    "threshold_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Porcentaje umbral",
                    ),
                ),
                (
                    "days_before_expiration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Días antes del vencimiento"
                    ),
                ),
                (
                    "send_email",
                    models.BooleanField(default=True, verbose_name="Enviar email"),
                ),
                (
                    "send_notification",
                    models.BooleanField(
                        default=True, verbose_name="Enviar notificación"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Inmediata"),
                            ("daily", "Diaria"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                        ],
                        default="immediate",
                        max_length=20,
                        verbose_name="Frecuencia",
                    ),
                ),
                (
                    "additional_emails",
                    models.TextField(
                        blank=True,
                        help_text="Emails adicionales separados por comas",
                        verbose_name="Emails adicionales",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Regla activa"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Regla de alerta",
                "verbose_name_plural": "Reglas de alertas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("in_app", "En aplicación"),
                            ("sms", "SMS"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de notificación",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(max_length=200, verbose_name="Destinatario"),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=200, verbose_name="Asunto"),
                ),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviada"),
                            ("failed", "Falló"),
                            ("delivered", "Entregada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="alerts.alert",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de notificación",
                "verbose_name_plural": "Logs de notificaciones",
                "ordering": ["-created_at"],
            },
        ),
    ]
