# Generated by Django 4.2.7 on 2025-07-02 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0001_initial"),
        ("alerts", "0001_initial"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                to="inventory.category",
                verbose_name="Categorías aplicables",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_rules",
                to="authentication.company",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_alert_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                to="inventory.location",
                verbose_name="Ubicaciones específicas",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="products",
            field=models.ManyToManyField(
                blank=True, to="inventory.product", verbose_name="Productos específicos"
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="recipients",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Destinatarios"
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="authentication.company",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="inventory.location",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="inventory.product",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="alerts.alertrule",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["company", "status"], name="alerts_aler_company_9bf118_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["company", "severity"], name="alerts_aler_company_afdc3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["product", "status"], name="alerts_aler_product_ef7964_idx"
            ),
        ),
    ]
