# Generated by Django 4.2.7 on 2025-07-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="additional_phones",
            field=models.TextField(
                blank=True,
                help_text="Números de WhatsApp adicionales separados por comas (formato: +51999999999)",
                verbose_name="Teléfonos WhatsApp adicionales",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="send_whatsapp",
            field=models.BooleanField(default=False, verbose_name="Enviar WhatsApp"),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="whatsapp_message_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ID mensaje WhatsApp"
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("whatsapp", "WhatsApp"),
                    ("in_app", "En aplicación"),
                    ("sms", "SMS"),
                    ("webhook", "Webhook"),
                ],
                max_length=20,
                verbose_name="Tipo de notificación",
            ),
        ),
    ]
