# Generated by Django 4.2.7 on 2025-07-13 03:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forecasting", "0002_alter_forecastmodel_mape"),
        ("alerts", "0003_alertrule_additional_phones_alertrule_send_whatsapp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={
                "ordering": ["-priority_score", "-created_at"],
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
            },
        ),
        migrations.AddField(
            model_name="alert",
            name="demand_forecast",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="forecasting.demandforecast",
                verbose_name="Pronóstico relacionado",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="forecast_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="forecasting.forecastmodel",
                verbose_name="Modelo de pronóstico relacionado",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="priority_score",
            field=models.IntegerField(
                default=50,
                help_text="Puntuación de 0-100 para ordenamiento",
                verbose_name="Puntuación de prioridad",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="recommended_actions",
            field=models.JSONField(
                default=list,
                help_text="Lista de acciones que el usuario puede tomar",
                verbose_name="Acciones recomendadas",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="reorder_recommendation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="forecasting.reorderrecommendation",
                verbose_name="Recomendación de reorden relacionada",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="source",
            field=models.CharField(
                choices=[
                    ("rule", "Regla configurada"),
                    ("system", "Sistema automático"),
                    ("forecast", "Módulo de predicciones"),
                    ("manual", "Creada manualmente"),
                ],
                default="rule",
                max_length=20,
                verbose_name="Origen",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="accuracy_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Para alertas de precisión de pronóstico",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Umbral de precisión (%)",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="forecast_horizon_days",
            field=models.PositiveIntegerField(
                blank=True,
                default=7,
                null=True,
                verbose_name="Horizonte de pronóstico (días)",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="seasonal_factor_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Para alertas de demanda estacional",
                max_digits=6,
                null=True,
                verbose_name="Factor estacional umbral",
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("low_stock", "Stock bajo"),
                    ("high_stock", "Stock alto"),
                    ("expiration", "Próximo a vencer"),
                    ("expired", "Vencido"),
                    ("high_demand", "Demanda alta proyectada"),
                    ("demand_vs_stock", "Demanda vs Stock insuficiente"),
                    ("stockout_risk", "Riesgo de agotamiento"),
                    ("reorder_urgent", "Reorden urgente"),
                    ("forecast_accuracy", "Precisión de pronóstico baja"),
                    ("seasonal_demand", "Demanda estacional"),
                    ("no_movement", "Sin movimiento"),
                    ("negative_stock", "Stock negativo"),
                    ("inventory_value", "Valor de inventario alto/bajo"),
                    ("supplier_delay", "Retraso de proveedor"),
                    ("abc_analysis", "Análisis ABC - Atención requerida"),
                ],
                max_length=30,
                verbose_name="Tipo de alerta",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["priority_score", "created_at"],
                name="alerts_aler_priorit_27387c_idx",
            ),
        ),
    ]
