# Generated by Django 4.2.7 on 2025-07-13 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_whatsapp_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alerts", "0004_alter_alert_options_alert_demand_forecast_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del destinatario"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Formato: +51999999999",
                        max_length=20,
                        null=True,
                        verbose_name="Teléfono WhatsApp",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("both", "Email y WhatsApp"),
                        ],
                        default="email",
                        max_length=20,
                        verbose_name="Tipo de notificación",
                    ),
                ),
                (
                    "receive_all_alerts",
                    models.BooleanField(
                        default=True, verbose_name="Recibir todas las alertas"
                    ),
                ),
                (
                    "receive_critical_only",
                    models.BooleanField(
                        default=False, verbose_name="Solo alertas críticas"
                    ),
                ),
                (
                    "receive_high_and_critical",
                    models.BooleanField(
                        default=False, verbose_name="Alertas altas y críticas"
                    ),
                ),
                (
                    "alert_types",
                    models.JSONField(
                        default=list,
                        help_text="Lista de tipos de alerta que este destinatario quiere recibir",
                        verbose_name="Tipos de alerta",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_recipients",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Destinatario de alertas",
                "verbose_name_plural": "Destinatarios de alertas",
                "ordering": ["name"],
                "unique_together": {("company", "email"), ("company", "phone")},
            },
        ),
    ]
