# Generated by Django 4.2.7 on 2025-07-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0005_alertrecipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="auto_generate_purchase_orders",
            field=models.BooleanField(
                default=False,
                help_text="Generar automáticamente órdenes de compra cuando se detecte stock bajo",
                verbose_name="Generar órdenes de compra automáticamente",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="auto_send_purchase_emails",
            field=models.BooleanField(
                default=True,
                help_text="Enviar automáticamente emails de órdenes de compra a proveedores",
                verbose_name="Enviar emails de órdenes automáticamente",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="purchase_order_priority",
            field=models.CharField(
                choices=[
                    ("low", "Baja"),
                    ("medium", "Media"),
                    ("high", "Alta"),
                    ("urgent", "Urgente"),
                ],
                default="medium",
                max_length=10,
                verbose_name="Prioridad de órdenes automáticas",
            ),
        ),
    ]
