# Generated by Django 4.2.7 on 2025-07-11 17:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_date",
                    models.DateField(verbose_name="Fecha del pronóstico"),
                ),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("daily", "Diario"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Tipo de pronóstico",
                    ),
                ),
                (
                    "predicted_demand",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Demanda pronosticada",
                    ),
                ),
                (
                    "lower_bound",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Límite inferior"
                    ),
                ),
                (
                    "upper_bound",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Límite superior"
                    ),
                ),
                (
                    "confidence_level",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Nivel de confianza",
                    ),
                ),
                (
                    "seasonality_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        verbose_name="Factor de estacionalidad",
                    ),
                ),
                (
                    "trend_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        verbose_name="Factor de tendencia",
                    ),
                ),
                (
                    "external_factors",
                    models.JSONField(default=dict, verbose_name="Factores externos"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_forecasts",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pronóstico de demanda",
                "verbose_name_plural": "Pronósticos de demanda",
                "ordering": ["forecast_date", "product"],
            },
        ),
        migrations.CreateModel(
            name="ForecastModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del modelo"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("prophet", "Facebook Prophet"),
                            ("arima", "ARIMA"),
                            ("linear_regression", "Regresión Lineal"),
                            ("random_forest", "Random Forest"),
                            ("lstm", "LSTM Neural Network"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de modelo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "Entrenando"),
                            ("active", "Activo"),
                            ("deprecated", "Depreciado"),
                            ("failed", "Falló"),
                        ],
                        default="training",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "forecast_horizon_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Horizonte de pronóstico (días)"
                    ),
                ),
                (
                    "training_period_days",
                    models.PositiveIntegerField(
                        default=365, verbose_name="Período de entrenamiento (días)"
                    ),
                ),
                (
                    "confidence_interval",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("95.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(99.99),
                        ],
                        verbose_name="Intervalo de confianza (%)",
                    ),
                ),
                (
                    "hyperparameters",
                    models.JSONField(default=dict, verbose_name="Hiperparámetros"),
                ),
                (
                    "mae",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Error Absoluto Medio",
                    ),
                ),
                (
                    "mape",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Error Porcentual Absoluto Medio",
                    ),
                ),
                (
                    "rmse",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Raíz del Error Cuadrático Medio",
                    ),
                ),
                (
                    "r2_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        verbose_name="Coeficiente de Determinación R²",
                    ),
                ),
                (
                    "model_file_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Ruta del archivo del modelo",
                    ),
                ),
                (
                    "model_size_mb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Tamaño del modelo (MB)",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Versión"
                    ),
                ),
                ("training_started_at", models.DateTimeField(blank=True, null=True)),
                ("training_completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_prediction_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        to="inventory.category",
                        verbose_name="Categorías aplicables",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_models",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_forecast_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_models",
                        to="forecasting.forecastmodel",
                        verbose_name="Modelo padre",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        to="inventory.product",
                        verbose_name="Productos aplicables",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de pronóstico",
                "verbose_name_plural": "Modelos de pronóstico",
                "ordering": ["-created_at"],
                "unique_together": {("company", "name", "version")},
            },
        ),
        migrations.CreateModel(
            name="ModelTrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("running", "Ejecutando"),
                            ("completed", "Completado"),
                            ("failed", "Falló"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "metrics",
                    models.JSONField(default=dict, verbose_name="Métricas obtenidas"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_training_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to="forecasting.forecastmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajo de entrenamiento",
                "verbose_name_plural": "Trabajos de entrenamiento",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForecastAccuracy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_demand",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Demanda real"
                    ),
                ),
                (
                    "absolute_error",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Error absoluto"
                    ),
                ),
                (
                    "percentage_error",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="Error porcentual"
                    ),
                ),
                (
                    "squared_error",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="Error cuadrático"
                    ),
                ),
                (
                    "within_bounds",
                    models.BooleanField(verbose_name="Dentro de los límites"),
                ),
                (
                    "bias",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Sesgo"
                    ),
                ),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "forecast",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accuracy",
                        to="forecasting.demandforecast",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precisión del pronóstico",
                "verbose_name_plural": "Precisiones de pronósticos",
                "ordering": ["-evaluated_at"],
            },
        ),
        migrations.AddField(
            model_name="demandforecast",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecasts",
                to="forecasting.forecastmodel",
            ),
        ),
        migrations.AddField(
            model_name="demandforecast",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demand_forecasts",
                to="inventory.product",
            ),
        ),
        migrations.CreateModel(
            name="ReorderRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommended_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Cantidad recomendada",
                    ),
                ),
                (
                    "current_stock",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Stock actual"
                    ),
                ),
                (
                    "projected_demand",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Demanda proyectada",
                    ),
                ),
                (
                    "recommended_order_date",
                    models.DateField(verbose_name="Fecha recomendada de orden"),
                ),
                (
                    "expected_stockout_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha esperada de agotamiento",
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        verbose_name="Tiempo de entrega (días)"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobada"),
                            ("ordered", "Ordenada"),
                            ("received", "Recibida"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Costo estimado"
                    ),
                ),
                (
                    "potential_lost_sales",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Ventas potenciales perdidas",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "justification",
                    models.TextField(
                        blank=True, verbose_name="Justificación de la recomendación"
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reorder_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "forecast_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reorder_recommendations",
                        to="forecasting.forecastmodel",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reorder_recommendations",
                        to="inventory.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reorder_recommendations",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recomendación de reorden",
                "verbose_name_plural": "Recomendaciones de reorden",
                "ordering": ["-priority", "recommended_order_date"],
                "indexes": [
                    models.Index(
                        fields=["product", "status"],
                        name="forecasting_product_480358_idx",
                    ),
                    models.Index(
                        fields=["recommended_order_date", "priority"],
                        name="forecasting_recomme_054395_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="demandforecast",
            index=models.Index(
                fields=["product", "forecast_date"],
                name="forecasting_product_820aef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="demandforecast",
            index=models.Index(
                fields=["forecast_date", "forecast_type"],
                name="forecasting_forecas_622006_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="demandforecast",
            unique_together={("product", "forecast_date", "forecast_type", "location")},
        ),
    ]
