# Generated by Django 4.2.7 on 2025-07-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecastmodel",
            name="mape",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Error Porcentual Absoluto Medio",
            ),
        ),
    ]
