# Generated by Django 4.2.7 on 2025-07-15 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_product_price"),
        ("authentication", "0002_user_whatsapp_notifications"),
        ("forecasting", "0002_alter_forecastmodel_mape"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialForecastModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del modelo"),
                ),
                (
                    "model_type",
                    models.CharField(max_length=50, verbose_name="Tipo de modelo"),
                ),
                (
                    "forecast_horizon_months",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Horizonte en meses"
                    ),
                ),
                (
                    "include_seasonality",
                    models.BooleanField(
                        default=True, verbose_name="Incluir estacionalidad"
                    ),
                ),
                (
                    "include_external_factors",
                    models.BooleanField(
                        default=False, verbose_name="Incluir factores externos"
                    ),
                ),
                (
                    "accuracy_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Precisión (%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_forecast_models",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de pronóstico financiero",
                "verbose_name_plural": "Modelos de pronóstico financiero",
            },
        ),
        migrations.CreateModel(
            name="NextPurchasePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_date", models.DateField(verbose_name="Fecha predicha")),
                (
                    "days_until_purchase",
                    models.PositiveIntegerField(verbose_name="Días hasta compra"),
                ),
                (
                    "confidence_level",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Nivel de confianza",
                    ),
                ),
                (
                    "predicted_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor predicho"
                    ),
                ),
                (
                    "predicted_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Cantidad predicha"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_purchase_predictions",
                        to="inventory.customer",
                    ),
                ),
                (
                    "recommended_products",
                    models.ManyToManyField(
                        blank=True,
                        to="inventory.product",
                        verbose_name="Productos recomendados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predicción de próxima compra",
                "verbose_name_plural": "Predicciones de próximas compras",
            },
        ),
        migrations.CreateModel(
            name="SupplierROIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Costo total"
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Ingresos totales"
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Ganancia bruta"
                    ),
                ),
                (
                    "roi_percentage",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="ROI (%)"
                    ),
                ),
                (
                    "avg_delivery_time",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Tiempo promedio entrega",
                    ),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Puntuación de calidad",
                    ),
                ),
                (
                    "on_time_delivery_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Tasa entrega a tiempo",
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Costo por unidad"
                    ),
                ),
                (
                    "cost_trend",
                    models.CharField(
                        choices=[
                            ("decreasing", "Disminuyendo"),
                            ("stable", "Estable"),
                            ("increasing", "Aumentando"),
                        ],
                        max_length=15,
                        verbose_name="Tendencia de costos",
                    ),
                ),
                (
                    "performance_rating",
                    models.CharField(
                        choices=[
                            ("excellent", "Excelente"),
                            ("good", "Bueno"),
                            ("average", "Promedio"),
                            ("poor", "Malo"),
                        ],
                        max_length=15,
                        verbose_name="Calificación de rendimiento",
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(default=list, verbose_name="Recomendaciones"),
                ),
                (
                    "analysis_start_date",
                    models.DateField(verbose_name="Fecha inicio análisis"),
                ),
                (
                    "analysis_end_date",
                    models.DateField(verbose_name="Fecha fin análisis"),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roi_analysis",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis ROI de proveedor",
                "verbose_name_plural": "Análisis ROI de proveedores",
                "ordering": ["-roi_percentage"],
            },
        ),
        migrations.CreateModel(
            name="PriceElasticityAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "elasticity_coefficient",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="Coeficiente"
                    ),
                ),
                (
                    "r_squared",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="R²"
                    ),
                ),
                (
                    "optimal_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio óptimo"
                    ),
                ),
                (
                    "price_sensitivity",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                        ],
                        max_length=20,
                        verbose_name="Sensibilidad",
                    ),
                ),
                (
                    "data_points",
                    models.PositiveIntegerField(verbose_name="Puntos de datos"),
                ),
                (
                    "analysis_period_days",
                    models.PositiveIntegerField(verbose_name="Período de análisis"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elasticity_analysis",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis de elasticidad de precio",
                "verbose_name_plural": "Análisis de elasticidad de precios",
            },
        ),
        migrations.CreateModel(
            name="PriceElasticity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "elasticity_coefficient",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=8,
                        verbose_name="Coeficiente de elasticidad",
                    ),
                ),
                (
                    "demand_sensitivity",
                    models.CharField(
                        choices=[
                            ("inelastic", "Inelástica"),
                            ("unit_elastic", "Unitaria"),
                            ("elastic", "Elástica"),
                            ("highly_elastic", "Muy elástica"),
                        ],
                        max_length=15,
                        verbose_name="Sensibilidad de demanda",
                    ),
                ),
                (
                    "optimal_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio óptimo"
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio actual"
                    ),
                ),
                (
                    "recommended_price_change",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Cambio recomendado (%)",
                    ),
                ),
                (
                    "estimated_demand_change",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=8,
                        verbose_name="Cambio estimado en demanda",
                    ),
                ),
                (
                    "estimated_revenue_impact",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Impacto estimado en ingresos",
                    ),
                ),
                (
                    "analysis_period_days",
                    models.PositiveIntegerField(
                        verbose_name="Período de análisis (días)"
                    ),
                ),
                (
                    "price_points_analyzed",
                    models.PositiveIntegerField(
                        verbose_name="Puntos de precio analizados"
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_elasticity",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elasticidad de precio",
                "verbose_name_plural": "Elasticidades de precio",
                "ordering": ["-estimated_revenue_impact"],
            },
        ),
        migrations.CreateModel(
            name="DemandPatternAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "has_weekly_pattern",
                    models.BooleanField(default=False, verbose_name="Patrón semanal"),
                ),
                (
                    "has_monthly_pattern",
                    models.BooleanField(default=False, verbose_name="Patrón mensual"),
                ),
                (
                    "has_seasonal_pattern",
                    models.BooleanField(
                        default=False, verbose_name="Patrón estacional"
                    ),
                ),
                (
                    "weekly_strength",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Fuerza semanal",
                    ),
                ),
                (
                    "monthly_strength",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Fuerza mensual",
                    ),
                ),
                (
                    "seasonal_strength",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Fuerza estacional",
                    ),
                ),
                (
                    "pattern_data",
                    models.JSONField(default=dict, verbose_name="Datos del patrón"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_patterns",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis de patrón de demanda",
                "verbose_name_plural": "Análisis de patrones de demanda",
            },
        ),
        migrations.CreateModel(
            name="CustomerSegmentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_segment",
                    models.CharField(
                        choices=[
                            ("vip", "VIP"),
                            ("frequent", "Frecuente"),
                            ("occasional", "Ocasional"),
                            ("new", "Nuevo"),
                            ("dormant", "Dormante"),
                            ("lost", "Perdido"),
                        ],
                        max_length=20,
                        verbose_name="Segmento principal",
                    ),
                ),
                (
                    "value_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Score de valor"
                    ),
                ),
                (
                    "frequency_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Score de frecuencia",
                    ),
                ),
                (
                    "recency_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Score de recencia"
                    ),
                ),
                (
                    "segment_attributes",
                    models.JSONField(
                        default=dict, verbose_name="Atributos del segmento"
                    ),
                ),
                (
                    "marketing_strategy",
                    models.CharField(
                        max_length=50, verbose_name="Estrategia de marketing"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmentation",
                        to="inventory.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Segmentación de cliente",
                "verbose_name_plural": "Segmentaciones de clientes",
            },
        ),
        migrations.CreateModel(
            name="CustomerLifetimeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "predicted_clv",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="CLV Predicho"
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor actual"
                    ),
                ),
                (
                    "predicted_lifetime_months",
                    models.PositiveIntegerField(verbose_name="Vida predicha (meses)"),
                ),
                (
                    "churn_probability",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Probabilidad de abandono",
                    ),
                ),
                (
                    "next_purchase_probability",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Probabilidad próxima compra",
                    ),
                ),
                (
                    "avg_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor promedio de orden",
                    ),
                ),
                (
                    "purchase_frequency",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=8,
                        verbose_name="Frecuencia de compra",
                    ),
                ),
                (
                    "last_purchase_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Última compra"
                    ),
                ),
                (
                    "customer_segment",
                    models.CharField(
                        choices=[
                            ("champion", "Campeón"),
                            ("loyal", "Leal"),
                            ("potential", "Potencial"),
                            ("new", "Nuevo"),
                            ("at_risk", "En riesgo"),
                            ("lost", "Perdido"),
                        ],
                        max_length=20,
                        verbose_name="Segmento de cliente",
                    ),
                ),
                (
                    "next_best_products",
                    models.JSONField(
                        default=list, verbose_name="Próximos mejores productos"
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifetime_value",
                        to="inventory.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de vida del cliente",
                "verbose_name_plural": "Valores de vida de clientes",
                "ordering": ["-predicted_clv"],
            },
        ),
        migrations.CreateModel(
            name="ChurnPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "churn_probability",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Probabilidad de abandono",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Bajo"),
                            ("medium", "Medio"),
                            ("high", "Alto"),
                            ("critical", "Crítico"),
                        ],
                        max_length=10,
                        verbose_name="Nivel de riesgo",
                    ),
                ),
                (
                    "days_since_last_purchase",
                    models.PositiveIntegerField(
                        verbose_name="Días desde última compra"
                    ),
                ),
                (
                    "purchase_frequency_decline",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=6,
                        verbose_name="Declive en frecuencia",
                    ),
                ),
                (
                    "value_decline",
                    models.DecimalField(
                        decimal_places=4, max_digits=6, verbose_name="Declive en valor"
                    ),
                ),
                (
                    "risk_factors",
                    models.JSONField(default=list, verbose_name="Factores de riesgo"),
                ),
                (
                    "retention_strategy",
                    models.CharField(
                        choices=[
                            ("discount", "Descuento"),
                            ("loyalty_program", "Programa de lealtad"),
                            ("personal_attention", "Atención personalizada"),
                            ("product_recommendation", "Recomendación de productos"),
                            ("contact_campaign", "Campaña de contacto"),
                        ],
                        max_length=30,
                        verbose_name="Estrategia de retención",
                    ),
                ),
                (
                    "retention_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Presupuesto de retención",
                    ),
                ),
                (
                    "strategy_applied",
                    models.BooleanField(
                        default=False, verbose_name="Estrategia aplicada"
                    ),
                ),
                (
                    "strategy_effective",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Estrategia efectiva"
                    ),
                ),
                ("predicted_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="churn_prediction",
                        to="inventory.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predicción de abandono",
                "verbose_name_plural": "Predicciones de abandono",
                "ordering": ["-churn_probability"],
            },
        ),
        migrations.CreateModel(
            name="TrendingProductPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_date",
                    models.DateField(verbose_name="Fecha de predicción"),
                ),
                (
                    "trend_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Score de tendencia",
                    ),
                ),
                (
                    "growth_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=8,
                        verbose_name="Tasa de crecimiento",
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Confianza"
                    ),
                ),
                ("factors", models.JSONField(default=list, verbose_name="Factores")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trending_predictions",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predicción de producto en tendencia",
                "verbose_name_plural": "Predicciones de productos en tendencia",
                "unique_together": {("product", "prediction_date")},
            },
        ),
        migrations.CreateModel(
            name="StockoutPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_date",
                    models.DateField(verbose_name="Fecha de predicción"),
                ),
                (
                    "predicted_stockout_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha predicha de agotamiento",
                    ),
                ),
                (
                    "stockout_probability",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Probabilidad de agotamiento",
                    ),
                ),
                (
                    "days_until_stockout",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Días hasta agotamiento"
                    ),
                ),
                (
                    "current_stock",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Stock actual"
                    ),
                ),
                (
                    "predicted_demand",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Demanda predicha"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stockout_predictions",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predicción de agotamiento",
                "verbose_name_plural": "Predicciones de agotamiento",
                "unique_together": {("product", "prediction_date")},
            },
        ),
        migrations.CreateModel(
            name="SeasonalityPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                            ("yearly", "Anual"),
                            ("holiday", "Festividades"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de patrón",
                    ),
                ),
                (
                    "pattern_strength",
                    models.DecimalField(
                        decimal_places=4, max_digits=6, verbose_name="Fuerza del patrón"
                    ),
                ),
                (
                    "peak_periods",
                    models.JSONField(default=list, verbose_name="Períodos pico"),
                ),
                (
                    "low_periods",
                    models.JSONField(default=list, verbose_name="Períodos bajos"),
                ),
                (
                    "seasonal_multipliers",
                    models.JSONField(
                        default=dict, verbose_name="Multiplicadores estacionales"
                    ),
                ),
                (
                    "data_points_analyzed",
                    models.PositiveIntegerField(
                        verbose_name="Puntos de datos analizados"
                    ),
                ),
                (
                    "pattern_confidence",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Confianza del patrón",
                    ),
                ),
                (
                    "next_peak_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima fecha pico"
                    ),
                ),
                (
                    "next_low_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima fecha baja"
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonality_patterns",
                        to="authentication.company",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonality_patterns",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patrón estacional",
                "verbose_name_plural": "Patrones estacionales",
                "ordering": ["-pattern_strength"],
                "unique_together": {("product", "pattern_type")},
            },
        ),
        migrations.CreateModel(
            name="RevenuePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_date",
                    models.DateField(verbose_name="Fecha de predicción"),
                ),
                (
                    "predicted_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Ingresos predichos",
                    ),
                ),
                (
                    "confidence_level",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Nivel de confianza",
                    ),
                ),
                (
                    "category_breakdown",
                    models.JSONField(
                        default=dict, verbose_name="Desglose por categoría"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_predictions",
                        to="forecasting.financialforecastmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predicción de ingresos",
                "verbose_name_plural": "Predicciones de ingresos",
                "unique_together": {("model", "prediction_date")},
            },
        ),
        migrations.CreateModel(
            name="RevenueForecasting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_date",
                    models.DateField(verbose_name="Fecha del pronóstico"),
                ),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                            ("yearly", "Anual"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de pronóstico",
                    ),
                ),
                (
                    "predicted_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Ingresos pronosticados",
                    ),
                ),
                (
                    "predicted_margin",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=8,
                        verbose_name="Margen pronosticado (%)",
                    ),
                ),
                (
                    "predicted_cashflow",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Flujo de caja pronosticado",
                    ),
                ),
                (
                    "revenue_lower_bound",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Límite inferior ingresos",
                    ),
                ),
                (
                    "revenue_upper_bound",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Límite superior ingresos",
                    ),
                ),
                (
                    "category_breakdown",
                    models.JSONField(
                        default=dict, verbose_name="Desglose por categorías"
                    ),
                ),
                (
                    "seasonality_impact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        verbose_name="Impacto estacional",
                    ),
                ),
                (
                    "trend_impact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        verbose_name="Impacto de tendencia",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("PEN", "Soles Peruanos"),
                            ("USD", "Dólares Americanos"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "confidence_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=95.0,
                        max_digits=5,
                        verbose_name="Nivel de confianza",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_forecasts",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pronóstico de ingresos",
                "verbose_name_plural": "Pronósticos de ingresos",
                "ordering": ["-forecast_date"],
                "unique_together": {("company", "forecast_date", "forecast_type")},
            },
        ),
        migrations.CreateModel(
            name="ProductRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("cross_sell", "Venta cruzada"),
                            ("up_sell", "Venta adicional"),
                            ("repeat_purchase", "Compra repetida"),
                            ("seasonal", "Estacional"),
                            ("trending", "Tendencia"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de recomendación",
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Puntuación de confianza",
                    ),
                ),
                (
                    "purchase_probability",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Probabilidad de compra",
                    ),
                ),
                (
                    "expected_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Cantidad esperada"
                    ),
                ),
                (
                    "expected_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Ingresos esperados",
                    ),
                ),
                ("reasoning", models.TextField(verbose_name="Razonamiento")),
                (
                    "similar_customers",
                    models.JSONField(default=list, verbose_name="Clientes similares"),
                ),
                (
                    "best_contact_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Mejor momento de contacto"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expira el")),
                (
                    "presented_to_customer",
                    models.BooleanField(
                        default=False, verbose_name="Presentado al cliente"
                    ),
                ),
                (
                    "customer_response",
                    models.CharField(
                        choices=[
                            ("accepted", "Aceptado"),
                            ("declined", "Rechazado"),
                            ("ignored", "Ignorado"),
                            ("pending", "Pendiente"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Respuesta del cliente",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_recommendations",
                        to="inventory.customer",
                    ),
                ),
                (
                    "next_purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_recommendations",
                        to="forecasting.nextpurchaseprediction",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_recommendations",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recomendación de producto",
                "verbose_name_plural": "Recomendaciones de productos",
                "ordering": ["-confidence_score"],
                "unique_together": {("customer", "product", "recommendation_type")},
            },
        ),
        migrations.CreateModel(
            name="OptimalStockLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "optimal_stock",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Stock óptimo"
                    ),
                ),
                (
                    "safety_stock",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Stock de seguridad",
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Punto de reorden"
                    ),
                ),
                (
                    "economic_order_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Cantidad económica de pedido",
                    ),
                ),
                (
                    "holding_cost_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=6,
                        verbose_name="Tasa de costo de mantenimiento",
                    ),
                ),
                (
                    "ordering_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Costo de pedido"
                    ),
                ),
                (
                    "stockout_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Costo de quiebre"
                    ),
                ),
                (
                    "avg_daily_demand",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Demanda diaria promedio",
                    ),
                ),
                (
                    "demand_variability",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=8,
                        verbose_name="Variabilidad de demanda",
                    ),
                ),
                (
                    "lead_time_variability",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Variabilidad tiempo entrega",
                    ),
                ),
                (
                    "expected_stockout_frequency",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=6,
                        verbose_name="Frecuencia esperada de quiebre",
                    ),
                ),
                (
                    "expected_annual_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Costo anual esperado",
                    ),
                ),
                (
                    "service_level",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Nivel de servicio (%)",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimal_stock_levels",
                        to="inventory.location",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimal_stock_level",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nivel de stock óptimo",
                "verbose_name_plural": "Niveles de stock óptimos",
                "ordering": ["-expected_annual_cost"],
                "unique_together": {("product", "location")},
            },
        ),
        migrations.CreateModel(
            name="MarketBasketAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "support",
                    models.DecimalField(
                        decimal_places=4, max_digits=6, verbose_name="Soporte"
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4, max_digits=6, verbose_name="Confianza"
                    ),
                ),
                (
                    "lift",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="Elevación"
                    ),
                ),
                (
                    "transactions_with_both",
                    models.PositiveIntegerField(verbose_name="Transacciones con ambos"),
                ),
                (
                    "transactions_with_a",
                    models.PositiveIntegerField(verbose_name="Transacciones con A"),
                ),
                (
                    "total_transactions",
                    models.PositiveIntegerField(verbose_name="Total transacciones"),
                ),
                (
                    "recommendation_strength",
                    models.CharField(
                        choices=[
                            ("weak", "Débil"),
                            ("moderate", "Moderada"),
                            ("strong", "Fuerte"),
                            ("very_strong", "Muy fuerte"),
                        ],
                        max_length=15,
                        verbose_name="Fuerza de recomendación",
                    ),
                ),
                (
                    "analysis_start_date",
                    models.DateField(verbose_name="Fecha inicio análisis"),
                ),
                (
                    "analysis_end_date",
                    models.DateField(verbose_name="Fecha fin análisis"),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_basket_analyses",
                        to="authentication.company",
                    ),
                ),
                (
                    "product_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basket_analyses_as_a",
                        to="inventory.product",
                    ),
                ),
                (
                    "product_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basket_analyses_as_b",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis de canasta de mercado",
                "verbose_name_plural": "Análisis de canasta de mercado",
                "ordering": ["-lift"],
                "unique_together": {("product_a", "product_b", "analysis_start_date")},
            },
        ),
    ]
