# Generated by Django 4.2.7 on 2025-07-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_whatsapp_notifications"),
        ("inventory", "0004_remove_product_price"),
        ("forecasting", "0003_financialforecastmodel_nextpurchaseprediction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryOptimizationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_type", models.CharField(max_length=50)),
                ("optimization_algorithm", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("parameters", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de optimización de inventario",
                "verbose_name_plural": "Modelos de optimización de inventario",
            },
        ),
        migrations.AlterModelOptions(
            name="forecastaccuracy",
            options={
                "ordering": ["-evaluated_at"],
                "verbose_name": "Precisión del pronóstico",
                "verbose_name_plural": "Precisión de pronósticos",
            },
        ),
        migrations.CreateModel(
            name="SupplierRiskAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_type", models.CharField(max_length=50)),
                ("risk_level", models.CharField(max_length=20)),
                ("probability", models.FloatField()),
                ("impact_score", models.FloatField()),
                ("mitigation_strategy", models.TextField()),
                ("analysis_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis de riesgo de proveedor",
                "verbose_name_plural": "Análisis de riesgo de proveedores",
            },
        ),
        migrations.CreateModel(
            name="SupplierPerformanceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_date", models.DateField()),
                ("performance_score", models.FloatField()),
                ("delivery_reliability", models.FloatField()),
                ("quality_score", models.FloatField()),
                ("cost_effectiveness", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de rendimiento de proveedor",
                "verbose_name_plural": "Modelos de rendimiento de proveedores",
            },
        ),
        migrations.CreateModel(
            name="StockLevelRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation_type", models.CharField(max_length=50)),
                ("recommended_stock", models.FloatField()),
                ("current_stock", models.FloatField()),
                ("safety_stock", models.FloatField()),
                ("priority", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forecasting.inventoryoptimizationmodel",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recomendación de nivel de stock",
                "verbose_name_plural": "Recomendaciones de nivel de stock",
            },
        ),
        migrations.CreateModel(
            name="SeasonalPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_type", models.CharField(max_length=50)),
                ("seasonal_factor", models.FloatField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patrón estacional",
                "verbose_name_plural": "Patrones estacionales",
            },
        ),
        migrations.CreateModel(
            name="SeasonalityAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_type", models.CharField(max_length=50)),
                ("analysis_date", models.DateField()),
                ("seasonal_factor", models.FloatField()),
                ("peak_period", models.CharField(max_length=100)),
                ("low_period", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis de estacionalidad",
                "verbose_name_plural": "Análisis de estacionalidad",
            },
        ),
        migrations.CreateModel(
            name="RevenueBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breakdown_type", models.CharField(max_length=50)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "revenue_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("percentage_of_total", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Desglose de ingresos",
                "verbose_name_plural": "Desgloses de ingresos",
            },
        ),
        migrations.CreateModel(
            name="ProfitMarginAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("margin_type", models.CharField(max_length=50)),
                ("analysis_date", models.DateField()),
                ("gross_margin", models.FloatField()),
                ("net_margin", models.FloatField()),
                ("trend_direction", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis de margen de beneficio",
                "verbose_name_plural": "Análisis de márgenes de beneficio",
            },
        ),
        migrations.CreateModel(
            name="ProfitabilityAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_type", models.CharField(max_length=50)),
                ("analysis_date", models.DateField()),
                ("profit_margin", models.FloatField()),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=15)),
                ("costs", models.DecimalField(decimal_places=2, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis de rentabilidad",
                "verbose_name_plural": "Análisis de rentabilidad",
            },
        ),
        migrations.CreateModel(
            name="ProcurementOptimization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("optimization_type", models.CharField(max_length=50)),
                ("recommended_quantity", models.FloatField()),
                ("recommended_timing", models.DateField()),
                ("cost_savings", models.DecimalField(decimal_places=2, max_digits=15)),
                ("analysis_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Optimización de procuramiento",
                "verbose_name_plural": "Optimizaciones de procuramiento",
            },
        ),
        migrations.CreateModel(
            name="PriceOptimization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("optimization_type", models.CharField(max_length=50)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "recommended_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("expected_demand_change", models.FloatField()),
                (
                    "revenue_impact",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("analysis_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Optimización de precio",
                "verbose_name_plural": "Optimizaciones de precio",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyProgramModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loyalty_score", models.FloatField()),
                ("loyalty_tier", models.CharField(max_length=50)),
                ("points_balance", models.IntegerField()),
                ("engagement_level", models.CharField(max_length=20)),
                ("next_reward_threshold", models.IntegerField()),
                ("analysis_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de programa de lealtad",
                "verbose_name_plural": "Modelos de programa de lealtad",
            },
        ),
        migrations.CreateModel(
            name="InventoryTurnoverAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_type", models.CharField(max_length=20)),
                ("turnover_ratio", models.FloatField()),
                ("days_in_inventory", models.IntegerField()),
                ("performance_category", models.CharField(max_length=50)),
                ("analysis_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis de rotación de inventario",
                "verbose_name_plural": "Análisis de rotación de inventario",
            },
        ),
        migrations.CreateModel(
            name="FinancialTrendAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trend_type", models.CharField(max_length=50)),
                ("analysis_date", models.DateField()),
                ("trend_strength", models.FloatField()),
                ("trend_direction", models.CharField(max_length=20)),
                ("forecast_reliability", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis de tendencia financiera",
                "verbose_name_plural": "Análisis de tendencias financieras",
            },
        ),
        migrations.CreateModel(
            name="FinancialScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario_type", models.CharField(max_length=50)),
                ("scenario_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("probability", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escenario financiero",
                "verbose_name_plural": "Escenarios financieros",
            },
        ),
        migrations.CreateModel(
            name="FinancialRiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_type", models.CharField(max_length=50)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Bajo"),
                            ("medium", "Medio"),
                            ("high", "Alto"),
                            ("critical", "Crítico"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assessment_date", models.DateField()),
                ("probability", models.FloatField()),
                ("impact_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación de riesgo financiero",
                "verbose_name_plural": "Evaluaciones de riesgo financiero",
            },
        ),
        migrations.CreateModel(
            name="DemandPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern_type", models.CharField(max_length=50)),
                ("pattern_date", models.DateField()),
                ("pattern_strength", models.FloatField()),
                ("frequency", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patrón de demanda",
                "verbose_name_plural": "Patrones de demanda",
            },
        ),
        migrations.CreateModel(
            name="CustomerSatisfactionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("satisfaction_score", models.FloatField()),
                ("feedback_sentiment", models.CharField(max_length=20)),
                ("key_factors", models.JSONField(default=dict)),
                ("improvement_suggestions", models.TextField()),
                ("analysis_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de satisfacción del cliente",
                "verbose_name_plural": "Modelos de satisfacción del cliente",
            },
        ),
        migrations.CreateModel(
            name="CustomerEngagementModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engagement_score", models.FloatField()),
                ("engagement_level", models.CharField(max_length=20)),
                ("interaction_frequency", models.FloatField()),
                ("preferred_channels", models.JSONField(default=list)),
                ("last_interaction", models.DateTimeField()),
                ("analysis_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de engagement de cliente",
                "verbose_name_plural": "Modelos de engagement de cliente",
            },
        ),
        migrations.CreateModel(
            name="CustomerBehaviorPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern_type", models.CharField(max_length=50)),
                ("behavior_category", models.CharField(max_length=50)),
                ("pattern_strength", models.FloatField()),
                ("frequency", models.CharField(max_length=50)),
                ("analysis_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patrón de comportamiento de cliente",
                "verbose_name_plural": "Patrones de comportamiento de clientes",
            },
        ),
        migrations.CreateModel(
            name="CrossSellModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation_score", models.FloatField()),
                ("confidence_level", models.FloatField()),
                ("historical_data_support", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crosssell_primary",
                        to="inventory.product",
                    ),
                ),
                (
                    "recommended_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crosssell_recommended",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de cross-sell",
                "verbose_name_plural": "Modelos de cross-sell",
            },
        ),
        migrations.CreateModel(
            name="CostOptimizationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("optimization_type", models.CharField(max_length=50)),
                ("current_cost", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "optimized_cost",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "savings_potential",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de optimización de costos",
                "verbose_name_plural": "Modelos de optimización de costos",
            },
        ),
        migrations.CreateModel(
            name="CashFlowForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("inflow", "Entrada"),
                            ("outflow", "Salida"),
                            ("net", "Neto"),
                        ],
                        max_length=50,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "predicted_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("confidence_level", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_flow_forecasts",
                        to="forecasting.financialforecastmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pronóstico de flujo de caja",
                "verbose_name_plural": "Pronósticos de flujo de caja",
            },
        ),
        migrations.CreateModel(
            name="AdvancedDemandForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_type", models.CharField(max_length=50)),
                ("forecast_date", models.DateField()),
                ("predicted_demand", models.FloatField()),
                ("confidence_interval", models.JSONField()),
                ("external_factors", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forecasting.forecastmodel",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pronóstico avanzado de demanda",
                "verbose_name_plural": "Pronósticos avanzados de demanda",
            },
        ),
    ]
