# Generated by Django 4.2.7 on 2025-07-17 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0002_user_whatsapp_notifications"),
        ("forecasting", "0004_inventoryoptimizationmodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="churnprediction",
            name="churn_risk_level",
            field=models.CharField(
                default="unknown", max_length=20, verbose_name="Nivel de riesgo churn"
            ),
        ),
        migrations.AddField(
            model_name="churnprediction",
            name="declining_order_value",
            field=models.BooleanField(
                default=False, verbose_name="Valor de orden en declive"
            ),
        ),
        migrations.AddField(
            model_name="churnprediction",
            name="declining_purchase_frequency",
            field=models.BooleanField(
                default=False, verbose_name="Frecuencia en declive"
            ),
        ),
        migrations.AddField(
            model_name="churnprediction",
            name="engagement_score",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=6,
                verbose_name="Puntaje engagement",
            ),
        ),
        migrations.AddField(
            model_name="churnprediction",
            name="loyalty_score",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=6,
                verbose_name="Puntaje lealtad",
            ),
        ),
        migrations.AddField(
            model_name="churnprediction",
            name="negative_trend_months",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Meses tendencia negativa"
            ),
        ),
        migrations.AddField(
            model_name="churnprediction",
            name="recommended_action_priority",
            field=models.CharField(
                default="low", max_length=20, verbose_name="Prioridad acción"
            ),
        ),
        migrations.AddField(
            model_name="customerlifetimevalue",
            name="average_order_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Valor promedio orden",
            ),
        ),
        migrations.AddField(
            model_name="customerlifetimevalue",
            name="clv_confidence",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=6,
                verbose_name="Confianza CLV",
            ),
        ),
        migrations.AddField(
            model_name="customerlifetimevalue",
            name="customer_lifespan_months",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Duración de vida (meses)"
            ),
        ),
        migrations.AddField(
            model_name="customerlifetimevalue",
            name="frequency_score",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Puntaje frecuencia (1-5)"
            ),
        ),
        migrations.AddField(
            model_name="customerlifetimevalue",
            name="monetary_score",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Puntaje monetario (1-5)"
            ),
        ),
        migrations.AddField(
            model_name="customerlifetimevalue",
            name="recency_days",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Días desde última compra"
            ),
        ),
        migrations.AddField(
            model_name="customerlifetimevalue",
            name="rfm_segment",
            field=models.CharField(
                default="unknown", max_length=20, verbose_name="Segmento RFM"
            ),
        ),
        migrations.AddField(
            model_name="financialforecastmodel",
            name="base_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_configs",
                to="forecasting.forecastmodel",
            ),
        ),
        migrations.AddField(
            model_name="financialforecastmodel",
            name="currency",
            field=models.CharField(default="PEN", max_length=10, verbose_name="Moneda"),
        ),
        migrations.AddField(
            model_name="financialforecastmodel",
            name="include_cost_tracking",
            field=models.BooleanField(
                default=True, verbose_name="Incluir seguimiento costos"
            ),
        ),
        migrations.AddField(
            model_name="financialforecastmodel",
            name="include_supplier_analysis",
            field=models.BooleanField(
                default=False, verbose_name="Incluir análisis proveedores"
            ),
        ),
        migrations.AddField(
            model_name="financialforecastmodel",
            name="metric_type",
            field=models.CharField(
                default="revenue", max_length=50, verbose_name="Tipo de métrica"
            ),
        ),
        migrations.AlterField(
            model_name="forecastmodel",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("prophet", "Facebook Prophet"),
                    ("arima", "ARIMA"),
                    ("linear_regression", "Regresión Lineal"),
                    ("random_forest", "Random Forest"),
                    ("randomforest", "Random Forest"),
                    ("lstm", "LSTM Neural Network"),
                ],
                max_length=50,
                verbose_name="Tipo de modelo",
            ),
        ),
        migrations.CreateModel(
            name="MLModelVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.CharField(max_length=20, verbose_name="Versión (ej: 1.0.0)"),
                ),
                (
                    "deployment_status",
                    models.CharField(
                        choices=[
                            ("development", "Desarrollo"),
                            ("testing", "Pruebas"),
                            ("staging", "Staging"),
                            ("production", "Producción"),
                            ("deprecated", "Depreciado"),
                            ("archived", "Archivado"),
                        ],
                        default="development",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("model_binary", models.BinaryField(blank=True, null=True)),
                ("model_path", models.CharField(blank=True, max_length=500)),
                (
                    "model_size_mb",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "training_accuracy",
                    models.DecimalField(decimal_places=4, max_digits=6, null=True),
                ),
                (
                    "validation_accuracy",
                    models.DecimalField(decimal_places=4, max_digits=6, null=True),
                ),
                (
                    "test_accuracy",
                    models.DecimalField(decimal_places=4, max_digits=6, null=True),
                ),
                ("training_start", models.DateTimeField(null=True)),
                ("training_end", models.DateTimeField(null=True)),
                ("training_duration_seconds", models.PositiveIntegerField(null=True)),
                ("training_samples", models.PositiveIntegerField(null=True)),
                (
                    "changelog",
                    models.TextField(blank=True, verbose_name="Registro de cambios"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas técnicas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_ml_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ml_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "forecast_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="forecasting.forecastmodel",
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_versions",
                        to="forecasting.mlmodelversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MLModelRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "governance_status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pendiente de Revisión"),
                            ("approved", "Aprobado"),
                            ("rejected", "Rechazado"),
                            ("requires_changes", "Requiere Cambios"),
                        ],
                        max_length=30,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("review_date", models.DateTimeField(null=True)),
                ("passes_validation", models.BooleanField(default=False)),
                ("validation_report", models.JSONField(default=dict)),
                ("compliance_checks", models.JSONField(default=dict)),
                (
                    "min_accuracy_threshold",
                    models.DecimalField(decimal_places=4, max_digits=6),
                ),
                (
                    "current_accuracy",
                    models.DecimalField(decimal_places=4, max_digits=6, null=True),
                ),
                ("performance_degradation_alert", models.BooleanField(default=False)),
                ("deployed_to_production", models.BooleanField(default=False)),
                ("deployment_date", models.DateTimeField(null=True)),
                ("rollback_plan", models.TextField(blank=True)),
                ("last_health_check", models.DateTimeField(null=True)),
                ("health_status", models.CharField(default="unknown", max_length=20)),
                ("monitoring_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registry_entry",
                        to="forecasting.mlmodelversion",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MLMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("mae", "Error Absoluto Medio"),
                            ("mse", "Error Cuadrático Medio"),
                            ("rmse", "Raíz del Error Cuadrático Medio"),
                            ("mape", "Error Porcentual Absoluto Medio"),
                            ("r2", "Coeficiente de Determinación"),
                            ("accuracy", "Precisión"),
                            ("precision", "Precisión Positiva"),
                            ("recall", "Recall"),
                            ("f1_score", "Puntaje F1"),
                            ("auc_roc", "Área bajo ROC"),
                            ("revenue_impact", "Impacto en Ingresos"),
                            ("cost_reduction", "Reducción de Costos"),
                            ("forecast_accuracy", "Precisión de Pronóstico"),
                            ("custom", "Métrica Personalizada"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                ("metric_value", models.DecimalField(decimal_places=6, max_digits=15)),
                (
                    "metric_context",
                    models.CharField(
                        choices=[
                            ("training", "Entrenamiento"),
                            ("validation", "Validación"),
                            ("test", "Prueba"),
                            ("production", "Producción"),
                        ],
                        max_length=20,
                    ),
                ),
                ("calculation_date", models.DateTimeField(auto_now_add=True)),
                ("dataset_size", models.PositiveIntegerField(null=True)),
                ("time_period_start", models.DateTimeField(null=True)),
                ("time_period_end", models.DateTimeField(null=True)),
                ("metric_config", models.JSONField(default=dict)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="forecasting.mlmodelversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-calculation_date"],
            },
        ),
        migrations.CreateModel(
            name="MLExperiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("experiment_id", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planificando"),
                            ("running", "Ejecutando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("algorithms_tested", models.JSONField(default=list)),
                ("hyperparameters", models.JSONField(default=dict)),
                ("dataset_config", models.JSONField(default=dict)),
                ("best_algorithm", models.CharField(blank=True, max_length=50)),
                (
                    "best_metric_value",
                    models.DecimalField(decimal_places=6, max_digits=15, null=True),
                ),
                ("winning_config", models.JSONField(default=dict)),
                ("start_time", models.DateTimeField(null=True)),
                ("end_time", models.DateTimeField(null=True)),
                ("duration_minutes", models.PositiveIntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiments",
                        to="forecasting.forecastmodel",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_experiments",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MLDatasetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("version", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("total_samples", models.PositiveIntegerField()),
                ("training_samples", models.PositiveIntegerField()),
                ("validation_samples", models.PositiveIntegerField()),
                ("test_samples", models.PositiveIntegerField()),
                (
                    "missing_values_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "outliers_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "data_quality_score",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("data_start_date", models.DateTimeField()),
                ("data_end_date", models.DateTimeField()),
                ("feature_columns", models.JSONField(default=list)),
                ("target_columns", models.JSONField(default=list)),
                ("feature_engineering_steps", models.JSONField(default=list)),
                ("dataset_path", models.CharField(max_length=500)),
                (
                    "dataset_size_mb",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("checksum", models.CharField(max_length=64)),
                ("transformation_pipeline", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_datasets",
                        to="authentication.company",
                    ),
                ),
                (
                    "source_datasets",
                    models.ManyToManyField(
                        blank=True, to="forecasting.mldatasetversion"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mlmodelversion",
            index=models.Index(
                fields=["forecast_model", "deployment_status"],
                name="forecasting_forecas_e99411_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodelversion",
            index=models.Index(
                fields=["is_active", "deployment_status"],
                name="forecasting_is_acti_39e0fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodelversion",
            index=models.Index(
                fields=["created_at"], name="forecasting_created_2ab2f9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mlmodelversion",
            unique_together={("forecast_model", "version")},
        ),
        migrations.AddIndex(
            model_name="mlmodelregistry",
            index=models.Index(
                fields=["governance_status"], name="forecasting_governa_eaa49c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodelregistry",
            index=models.Index(
                fields=["deployed_to_production"], name="forecasting_deploye_cc035a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodelregistry",
            index=models.Index(
                fields=["performance_degradation_alert"],
                name="forecasting_perform_ad6dd4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mlmetric",
            index=models.Index(
                fields=["model_version", "metric_type"],
                name="forecasting_model_v_ff15fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mlmetric",
            index=models.Index(
                fields=["metric_type", "calculation_date"],
                name="forecasting_metric__a42cea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mlmetric",
            index=models.Index(
                fields=["model_version", "metric_context"],
                name="forecasting_model_v_ab5168_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mlexperiment",
            index=models.Index(
                fields=["company", "status"], name="forecasting_company_e53abb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlexperiment",
            index=models.Index(
                fields=["base_model", "created_at"],
                name="forecasting_base_mo_dc7bef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mlexperiment",
            index=models.Index(
                fields=["status", "created_at"], name="forecasting_status_3264e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mldatasetversion",
            index=models.Index(
                fields=["company", "name"], name="forecasting_company_d82f73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mldatasetversion",
            index=models.Index(
                fields=["data_start_date", "data_end_date"],
                name="forecasting_data_st_fb9b59_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mldatasetversion",
            unique_together={("name", "version", "company")},
        ),
    ]
