# Generated by Django 4.2.7 on 2025-07-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasting", "0005_ml_foundation_architecture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="churnprediction",
            name="churn_probability",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=5,
                verbose_name="Probabilidad de abandono",
            ),
        ),
        migrations.AlterField(
            model_name="churnprediction",
            name="days_since_last_purchase",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Días desde última compra"
            ),
        ),
        migrations.AlterField(
            model_name="churnprediction",
            name="purchase_frequency_decline",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=6,
                verbose_name="Declive en frecuencia",
            ),
        ),
        migrations.AlterField(
            model_name="churnprediction",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("low", "Bajo"),
                    ("medium", "Medio"),
                    ("high", "Alto"),
                    ("critical", "Crítico"),
                ],
                default="low",
                max_length=10,
                verbose_name="Nivel de riesgo",
            ),
        ),
        migrations.AlterField(
            model_name="churnprediction",
            name="value_decline",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=6,
                verbose_name="Declive en valor",
            ),
        ),
        migrations.AlterField(
            model_name="customerlifetimevalue",
            name="avg_order_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Valor promedio de orden",
            ),
        ),
        migrations.AlterField(
            model_name="customerlifetimevalue",
            name="churn_probability",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=5,
                verbose_name="Probabilidad de abandono",
            ),
        ),
        migrations.AlterField(
            model_name="customerlifetimevalue",
            name="current_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Valor actual",
            ),
        ),
        migrations.AlterField(
            model_name="customerlifetimevalue",
            name="next_purchase_probability",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=5,
                verbose_name="Probabilidad próxima compra",
            ),
        ),
        migrations.AlterField(
            model_name="customerlifetimevalue",
            name="predicted_lifetime_months",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Vida predicha (meses)"
            ),
        ),
        migrations.AlterField(
            model_name="customerlifetimevalue",
            name="purchase_frequency",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=8,
                verbose_name="Frecuencia de compra",
            ),
        ),
    ]
