# Generated by Django 4.2.7 on 2025-07-18 00:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_whatsapp_notifications"),
        ("inventory", "0004_remove_product_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forecasting", "0006_fix_model_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAPIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google AI"),
                            ("azure", "Azure OpenAI"),
                            ("aws", "AWS Bedrock"),
                            ("custom", "API Personalizada"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Nombre del modelo"),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("completion", "Text Completion"),
                            ("chat", "Chat Completion"),
                            ("embedding", "Embeddings"),
                            ("fine_tuning", "Fine-tuning"),
                            ("image_generation", "Generación de Imagen"),
                            ("image_analysis", "Análisis de Imagen"),
                            ("speech_to_text", "Speech to Text"),
                            ("text_to_speech", "Text to Speech"),
                        ],
                        max_length=20,
                    ),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "input_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "output_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("status_code", models.PositiveIntegerField(default=200)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                (
                    "request_context",
                    models.JSONField(default=dict, verbose_name="Contexto del request"),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_api_usage",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="AIPromptVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del prompt"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("sentiment_analysis", "Análisis de Sentimiento"),
                            ("strategy_recommendation", "Recomendación de Estrategia"),
                            ("customer_insight", "Insight de Cliente"),
                            ("demand_prediction", "Predicción de Demanda"),
                            ("product_recommendation", "Recomendación de Producto"),
                            ("market_analysis", "Análisis de Mercado"),
                            ("risk_assessment", "Evaluación de Riesgo"),
                            ("optimization", "Optimización"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "version",
                    models.CharField(max_length=20, verbose_name="Versión (ej: 1.0.0)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("testing", "En Pruebas"),
                            ("active", "Activo"),
                            ("deprecated", "Depreciado"),
                            ("archived", "Archivado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("system_prompt", models.TextField(verbose_name="System prompt")),
                (
                    "user_prompt_template",
                    models.TextField(verbose_name="Template del user prompt"),
                ),
                (
                    "assistant_prompt",
                    models.TextField(blank=True, verbose_name="Assistant prompt"),
                ),
                (
                    "ai_model",
                    models.CharField(
                        default="gpt-4", max_length=100, verbose_name="Modelo AI"
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.7"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                ("max_tokens", models.PositiveIntegerField(default=1000)),
                (
                    "top_p",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.0"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "avg_response_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "success_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("avg_tokens_used", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "test_group",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Grupo de prueba"
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ai_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_versions",
                        to="forecasting.aipromptversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("sentiment_analysis", "Análisis de Sentimiento"),
                            ("customer_behavior", "Comportamiento del Cliente"),
                            ("market_trend", "Tendencia de Mercado"),
                            ("demand_pattern", "Patrón de Demanda"),
                            ("pricing_strategy", "Estrategia de Precios"),
                            ("inventory_optimization", "Optimización de Inventario"),
                            ("risk_assessment", "Evaluación de Riesgo"),
                            (
                                "opportunity_identification",
                                "Identificación de Oportunidades",
                            ),
                            ("strategy_recommendation", "Recomendación de Estrategia"),
                            ("performance_analysis", "Análisis de Performance"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Título del insight"),
                ),
                ("description", models.TextField(verbose_name="Descripción detallada")),
                (
                    "insight_data",
                    models.JSONField(
                        default=dict, verbose_name="Datos estructurados del insight"
                    ),
                ),
                (
                    "raw_ai_response",
                    models.TextField(verbose_name="Respuesta completa de AI"),
                ),
                (
                    "sentiment_score",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_negative", "Muy Negativo"),
                            ("negative", "Negativo"),
                            ("neutral", "Neutral"),
                            ("positive", "Positivo"),
                            ("very_positive", "Muy Positivo"),
                        ],
                        max_length=20,
                        verbose_name="Puntuación de sentimiento",
                    ),
                ),
                (
                    "sentiment_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(default=list, verbose_name="Recomendaciones"),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("very_high", "Muy Alta"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("human_validated", models.BooleanField(default=False)),
                ("validation_feedback", models.TextField(blank=True)),
                (
                    "impact_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "business_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("implemented", models.BooleanField(default=False)),
                ("implementation_notes", models.TextField(blank=True)),
                ("implementation_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_usage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_insights",
                        to="forecasting.aiapiusage",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prompt_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_insights",
                        to="forecasting.aipromptversion",
                    ),
                ),
                (
                    "related_customers",
                    models.ManyToManyField(
                        blank=True, related_name="ai_insights", to="inventory.customer"
                    ),
                ),
                (
                    "related_products",
                    models.ManyToManyField(
                        blank=True, related_name="ai_insights", to="inventory.product"
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="aiapiusage",
            name="prompt_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_usage",
                to="forecasting.aipromptversion",
            ),
        ),
        migrations.AddField(
            model_name="aiapiusage",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_api_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="HybridMLAIPrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("demand_forecast", "Pronóstico de Demanda"),
                            ("customer_churn", "Abandono de Cliente"),
                            ("customer_clv", "Valor de Vida del Cliente"),
                            ("inventory_optimization", "Optimización de Inventario"),
                            ("pricing_optimization", "Optimización de Precios"),
                            ("market_expansion", "Expansión de Mercado"),
                            ("risk_assessment", "Evaluación de Riesgo"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la predicción"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "ml_prediction",
                    models.JSONField(default=dict, verbose_name="Predicción ML"),
                ),
                (
                    "ml_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "ai_prediction",
                    models.JSONField(default=dict, verbose_name="Predicción AI"),
                ),
                (
                    "ai_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "final_prediction",
                    models.JSONField(
                        default=dict, verbose_name="Predicción final híbrida"
                    ),
                ),
                (
                    "hybrid_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "ml_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.5"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "ai_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.5"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "actual_outcome",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Resultado real"
                    ),
                ),
                (
                    "accuracy_ml",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "accuracy_ai",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "accuracy_hybrid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ai_insight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hybrid_predictions",
                        to="forecasting.aiinsight",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hybrid_predictions",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_hybrid_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ml_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hybrid_predictions",
                        to="forecasting.forecastmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "prediction_type"],
                        name="forecasting_company_3cb2f5_idx",
                    ),
                    models.Index(
                        fields=["hybrid_confidence", "created_at"],
                        name="forecasting_hybrid__d05d2b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="forecasting_created_2e2091_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="aipromptversion",
            index=models.Index(
                fields=["prompt_type", "status"], name="forecasting_prompt__b00e00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aipromptversion",
            index=models.Index(
                fields=["is_active", "status"], name="forecasting_is_acti_64d02b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aipromptversion",
            index=models.Index(
                fields=["created_at"], name="forecasting_created_619046_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aipromptversion",
            unique_together={("name", "version")},
        ),
        migrations.AddIndex(
            model_name="aiinsight",
            index=models.Index(
                fields=["company", "insight_type"],
                name="forecasting_company_bef148_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiinsight",
            index=models.Index(
                fields=["confidence_level", "created_at"],
                name="forecasting_confide_aeb7d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiinsight",
            index=models.Index(
                fields=["priority_level", "implemented"],
                name="forecasting_priorit_d0bfe5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiinsight",
            index=models.Index(
                fields=["sentiment_score", "created_at"],
                name="forecasting_sentime_9966d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiapiusage",
            index=models.Index(
                fields=["company", "requested_at"],
                name="forecasting_company_aec0c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiapiusage",
            index=models.Index(
                fields=["api_provider", "model_name"],
                name="forecasting_api_pro_f22d46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiapiusage",
            index=models.Index(
                fields=["success", "requested_at"],
                name="forecasting_success_995197_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiapiusage",
            index=models.Index(
                fields=["total_cost", "requested_at"],
                name="forecasting_total_c_3cabb8_idx",
            ),
        ),
    ]
